# https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html
block-list-secret-scan: []
directory:
  - .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
  - terraform
  - dockerfile
mask: []
secrets-history-timeout: 12h
secrets-scan-file-type: []
summary-position: bottom
skip-check:
  - CKV_AWS_91   # Ensure the ELBv2 (Application/Network) has access logging enabled
  - CKV_AWS_115  # Ensure that AWS Lambda function is configured for function-level concurrent execution limit
  - CKV_AWS_116  # Ensure that AWS Lambda function is configured for a Dead Letter Queue (DLQ)
  - CKV_AWS_117  # AWS Lambda Function is not assigned to access within VPC (false-positive, DNS-RR static-ip lambda does not require VPC access)
  - CKV_AWS_119  # Ensure DynamoDB Tables are encrypted using a KMS Customer Managed CMK (unnecessary, FSID table holds non-sensitive path<->fsid mappings, SSE with the AWS managed aws/dynamodb key is sufficient)
  - CKV_AWS_124  # Ensure that CloudFormation stacks are sending event notifications to an SNS topic (false-positive, not applicable)
  - CKV_AWS_149  # Ensure that Secrets Manager secret is encrypted using KMS CMK
  - CKV_AWS_150  # Ensure that Load Balancer has deletion protection enabled
  - CKV_AWS_152  # Ensure that Load Balancer (Network/Gateway) has cross-zone load balancing enabled (false-positive, single az-bound)
  - CKV_AWS_158  # Ensure that CloudWatch Log Group is encrypted by KMS (false-positive, encrypted by default)
  - CKV_AWS_173  # Check encryption settings for Lambda environmental variable (false-positive, encrypted by default)
  - CKV_AWS_178  # Ensure fx ontap file system is encrypted by KMS using a customer managed Key (CMK)
  - CKV_AWS_203  # Ensure resource is encrypted by KMS using a customer managed Key (CMK) (false-positive, encrypted by default)
  - CKV_AWS_272  # Ensure AWS Lambda function is configured to validate code-signing
  - CKV_AWS_337  # Ensure SSM parameters are using KMS CMK (unneccesary, encrypted by AWS managed key, non-sensitive data)
  - CKV_AWS_338  # Ensure CloudWatch log groups retains logs for at least 1 year (30 days is acceptable)
  - CKV2_AWS_5   # Ensure that Security Groups are attached to another resource (false-positive, sg is attached via launch_template)
  - CKV2_AWS_23  # Route53 A Record has Attached Resource (not relevant)
  - CKV2_AWS_38  # Ensure Domain Name System Security Extensions (DNSSEC) signing is enabled for Amazon Route 53 public hosted zones (false-positive, DNS private-zone not applicable)
  - CKV2_AWS_39  # Ensure Domain Name System (DNS) query logging is enabled for Amazon Route 53 hosted zones (false-positive, DNS private-zone not applicable)
  - CKV2_AWS_57  # Ensure Secrets Manager secrets should have automatic rotation enabled
  - CKV2_AWS_74  # Ensure AWS Load Balancers use strong ciphers (false-positive as we only use NLB, bug in checkov v3.2.407, waiting for fix)
  - CKV_DOCKER_3 # Ensure that a user for the container has been created
  - CKV_DOCKER_7 # Ensure the base image uses a non latest version tag
compact: true # For the CLI output, do not display code blocks
quiet: true # For the CLI output, display only failed checks. Also disables progress bars
