# https://aquasecurity.github.io/tfsec/v1.28.11/guides/configuration/config/
exclude:
  - google-iam-no-privileged-service-accounts
  - google-compute-no-project-wide-ssh-keys
  - google-compute-enable-shielded-vm-vtpm
  - google-compute-enable-shielded-vm-im
  - google-compute-vm-disk-encryption-customer-key
  - google-compute-enable-vpc-flow-logs
  - google-compute-disk-encryption-customer-key
  - google-compute-no-public-ingress
  - aws-rds-enable-deletion-protection
  - aws-rds-enable-performance-insights-encryption
  - aws-cloudwatch-log-group-customer-key
