# https://trivy.dev/docs/latest/guide/configuration/filtering/#trivyignoreyaml
misconfigurations:
  - id: DS-0002
    paths:
      - "image/resources/startup/tests/Dockerfile"
      - "deployment/database/resources/Dockerfile"
  - id: DS-0010
    paths:
      - ".devcontainer/dev/Dockerfile"
      - ".devcontainer/prod/Dockerfile"
  - id: DS-0029
    paths:
      - ".devcontainer/dev/Dockerfile"
      - ".devcontainer/prod/Dockerfile"
  - id: AWS-0017
    paths:
      - "deployment/database/main.tf"
      - "deployment/terraform-module-knfsd/modules/dns_round_robin/lambda.tf"
  - id: AWS-0078
    paths:
      - "deployment/database/main.tf"
  - id: AWS-0098
    paths:
      - "examples/fsx-netapp/main.tf"
  - id: AWS-0104
    paths:
      - "deployment/terraform-module-knfsd/vpc.tf"
      - "image/smoke-tests/terraform/network.tf"
  - id: AWS-0177
    paths:
      - "deployment/database/main.tf"
  - id: AWS-0344
    paths:
      - "examples/fsx-netapp/main.tf"
      - "examples/fsx-zfs/main.tf"
      - "examples/fsx-zfs-fanout-dns-rr/main.tf"
      - "examples/fsx-zfs-fanout-loadbalancer/main.tf"
      - "image/smoke-tests/modules/nfs-client/main.tf"
      - "image/smoke-tests/modules/source-nfs/main.tf"
      - "image/smoke-tests/terraform/network.tf"

vulnerabilities:
  - id: GO-2026-5932
    paths:
      - "image/resources/knfsd-metrics-agent/go.mod"
      - "image/smoke-tests/go.mod"

licenses:
  - id: Apache-2.0
  - id: BSD-2-Clause
  - id: BSD-3-Clause
  - id: ISC
  - id: MIT
  - id: MPL-2.0
  - id: Unicode-DFS-2016
