// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					NfsMountOperationErrors:        MetricConfig{Enabled: true},
					NfsMountOperationMajorTimeouts: MetricConfig{Enabled: true},
					NfsMountOperationReceivedBytes: MetricConfig{Enabled: true},
					NfsMountOperationRequests:      MetricConfig{Enabled: true},
					NfsMountOperationSentBytes:     MetricConfig{Enabled: true},
					NfsMountOpsPerSecond:           MetricConfig{Enabled: true},
					NfsMountReadBytes:              MetricConfig{Enabled: true},
					NfsMountReadExe:                MetricConfig{Enabled: true},
					NfsMountReadRtt:                MetricConfig{Enabled: true},
					NfsMountRPCBacklog:             MetricConfig{Enabled: true},
					NfsMountWriteBytes:             MetricConfig{Enabled: true},
					NfsMountWriteExe:               MetricConfig{Enabled: true},
					NfsMountWriteRtt:               MetricConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					NfsMountOperationErrors:        MetricConfig{Enabled: false},
					NfsMountOperationMajorTimeouts: MetricConfig{Enabled: false},
					NfsMountOperationReceivedBytes: MetricConfig{Enabled: false},
					NfsMountOperationRequests:      MetricConfig{Enabled: false},
					NfsMountOperationSentBytes:     MetricConfig{Enabled: false},
					NfsMountOpsPerSecond:           MetricConfig{Enabled: false},
					NfsMountReadBytes:              MetricConfig{Enabled: false},
					NfsMountReadExe:                MetricConfig{Enabled: false},
					NfsMountReadRtt:                MetricConfig{Enabled: false},
					NfsMountRPCBacklog:             MetricConfig{Enabled: false},
					NfsMountWriteBytes:             MetricConfig{Enabled: false},
					NfsMountWriteExe:               MetricConfig{Enabled: false},
					NfsMountWriteRtt:               MetricConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
