// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0
			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNfsMountOperationErrorsDataPoint(ts, 1, "server-val", "instance-val", "operation-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNfsMountOperationMajorTimeoutsDataPoint(ts, 1, "server-val", "instance-val", "operation-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNfsMountOperationReceivedBytesDataPoint(ts, 1, "server-val", "instance-val", "operation-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNfsMountOperationRequestsDataPoint(ts, 1, "server-val", "instance-val", "operation-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNfsMountOperationSentBytesDataPoint(ts, 1, "server-val", "instance-val", "operation-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNfsMountOpsPerSecondDataPoint(ts, 1, "server-val", "instance-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNfsMountReadBytesDataPoint(ts, 1, "server-val", "instance-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNfsMountReadExeDataPoint(ts, 1, "server-val", "instance-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNfsMountReadRttDataPoint(ts, 1, "server-val", "instance-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNfsMountRPCBacklogDataPoint(ts, 1, "server-val", "instance-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNfsMountWriteBytesDataPoint(ts, 1, "server-val", "instance-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNfsMountWriteExeDataPoint(ts, 1, "server-val", "instance-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNfsMountWriteRttDataPoint(ts, 1, "server-val", "instance-val")

			res := pcommon.NewResource()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			assert.Equal(t, 1, metrics.ResourceMetrics().Len())
			rm := metrics.ResourceMetrics().At(0)
			assert.Equal(t, res, rm.Resource())
			assert.Equal(t, 1, rm.ScopeMetrics().Len())
			ms := rm.ScopeMetrics().At(0).Metrics()
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, ms.Len())
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, ms.Len())
			}
			validatedMetrics := make(map[string]bool)
			for i := 0; i < ms.Len(); i++ {
				switch ms.At(i).Name() {
				case "nfs.mount.operation.errors":
					assert.False(t, validatedMetrics["nfs.mount.operation.errors"], "Found a duplicate in the metrics slice: nfs.mount.operation.errors")
					validatedMetrics["nfs.mount.operation.errors"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Number of requests that complete with tk_status < 0", ms.At(i).Description())
					assert.Equal(t, "{errors}", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("server")
					assert.True(t, ok)
					assert.Equal(t, "server-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("instance")
					assert.True(t, ok)
					assert.Equal(t, "instance-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("operation")
					assert.True(t, ok)
					assert.Equal(t, "operation-val", attrVal.Str())
				case "nfs.mount.operation.major_timeouts":
					assert.False(t, validatedMetrics["nfs.mount.operation.major_timeouts"], "Found a duplicate in the metrics slice: nfs.mount.operation.major_timeouts")
					validatedMetrics["nfs.mount.operation.major_timeouts"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Number of times a request has had a major timeout", ms.At(i).Description())
					assert.Equal(t, "{timeouts}", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("server")
					assert.True(t, ok)
					assert.Equal(t, "server-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("instance")
					assert.True(t, ok)
					assert.Equal(t, "instance-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("operation")
					assert.True(t, ok)
					assert.Equal(t, "operation-val", attrVal.Str())
				case "nfs.mount.operation.received_bytes":
					assert.False(t, validatedMetrics["nfs.mount.operation.received_bytes"], "Found a duplicate in the metrics slice: nfs.mount.operation.received_bytes")
					validatedMetrics["nfs.mount.operation.received_bytes"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Total bytes received for these operations, including RPC headers and payload", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("server")
					assert.True(t, ok)
					assert.Equal(t, "server-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("instance")
					assert.True(t, ok)
					assert.Equal(t, "instance-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("operation")
					assert.True(t, ok)
					assert.Equal(t, "operation-val", attrVal.Str())
				case "nfs.mount.operation.requests":
					assert.False(t, validatedMetrics["nfs.mount.operation.requests"], "Found a duplicate in the metrics slice: nfs.mount.operation.requests")
					validatedMetrics["nfs.mount.operation.requests"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Number of requests", ms.At(i).Description())
					assert.Equal(t, "{requests}", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("server")
					assert.True(t, ok)
					assert.Equal(t, "server-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("instance")
					assert.True(t, ok)
					assert.Equal(t, "instance-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("operation")
					assert.True(t, ok)
					assert.Equal(t, "operation-val", attrVal.Str())
				case "nfs.mount.operation.sent_bytes":
					assert.False(t, validatedMetrics["nfs.mount.operation.sent_bytes"], "Found a duplicate in the metrics slice: nfs.mount.operation.sent_bytes")
					validatedMetrics["nfs.mount.operation.sent_bytes"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Total bytes sent for these operations, including RPC headers and payload", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("server")
					assert.True(t, ok)
					assert.Equal(t, "server-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("instance")
					assert.True(t, ok)
					assert.Equal(t, "instance-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("operation")
					assert.True(t, ok)
					assert.Equal(t, "operation-val", attrVal.Str())
				case "nfs.mount.ops_per_second":
					assert.False(t, validatedMetrics["nfs.mount.ops_per_second"], "Found a duplicate in the metrics slice: nfs.mount.ops_per_second")
					validatedMetrics["nfs.mount.ops_per_second"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "nfsiostat Mount Operations Per Second", ms.At(i).Description())
					assert.Equal(t, "{count}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("server")
					assert.True(t, ok)
					assert.Equal(t, "server-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("instance")
					assert.True(t, ok)
					assert.Equal(t, "instance-val", attrVal.Str())
				case "nfs.mount.read_bytes":
					assert.False(t, validatedMetrics["nfs.mount.read_bytes"], "Found a duplicate in the metrics slice: nfs.mount.read_bytes")
					validatedMetrics["nfs.mount.read_bytes"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Bytes read from remote NFS server", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("server")
					assert.True(t, ok)
					assert.Equal(t, "server-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("instance")
					assert.True(t, ok)
					assert.Equal(t, "instance-val", attrVal.Str())
				case "nfs.mount.read_exe":
					assert.False(t, validatedMetrics["nfs.mount.read_exe"], "Found a duplicate in the metrics slice: nfs.mount.read_exe")
					validatedMetrics["nfs.mount.read_exe"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "nfsiostat Mount Read EXE", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("server")
					assert.True(t, ok)
					assert.Equal(t, "server-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("instance")
					assert.True(t, ok)
					assert.Equal(t, "instance-val", attrVal.Str())
				case "nfs.mount.read_rtt":
					assert.False(t, validatedMetrics["nfs.mount.read_rtt"], "Found a duplicate in the metrics slice: nfs.mount.read_rtt")
					validatedMetrics["nfs.mount.read_rtt"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "nfsiostat Mount Read RTT", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("server")
					assert.True(t, ok)
					assert.Equal(t, "server-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("instance")
					assert.True(t, ok)
					assert.Equal(t, "instance-val", attrVal.Str())
				case "nfs.mount.rpc_backlog":
					assert.False(t, validatedMetrics["nfs.mount.rpc_backlog"], "Found a duplicate in the metrics slice: nfs.mount.rpc_backlog")
					validatedMetrics["nfs.mount.rpc_backlog"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "nfsiostat Mount RPC Backlog", ms.At(i).Description())
					assert.Equal(t, "{count}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("server")
					assert.True(t, ok)
					assert.Equal(t, "server-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("instance")
					assert.True(t, ok)
					assert.Equal(t, "instance-val", attrVal.Str())
				case "nfs.mount.write_bytes":
					assert.False(t, validatedMetrics["nfs.mount.write_bytes"], "Found a duplicate in the metrics slice: nfs.mount.write_bytes")
					validatedMetrics["nfs.mount.write_bytes"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Bytes wrote to remote NFS server", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("server")
					assert.True(t, ok)
					assert.Equal(t, "server-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("instance")
					assert.True(t, ok)
					assert.Equal(t, "instance-val", attrVal.Str())
				case "nfs.mount.write_exe":
					assert.False(t, validatedMetrics["nfs.mount.write_exe"], "Found a duplicate in the metrics slice: nfs.mount.write_exe")
					validatedMetrics["nfs.mount.write_exe"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "nfsiostat Mount Write EXE", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("server")
					assert.True(t, ok)
					assert.Equal(t, "server-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("instance")
					assert.True(t, ok)
					assert.Equal(t, "instance-val", attrVal.Str())
				case "nfs.mount.write_rtt":
					assert.False(t, validatedMetrics["nfs.mount.write_rtt"], "Found a duplicate in the metrics slice: nfs.mount.write_rtt")
					validatedMetrics["nfs.mount.write_rtt"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "nfsiostat Mount Write RTT", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("server")
					assert.True(t, ok)
					assert.Equal(t, "server-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("instance")
					assert.True(t, ok)
					assert.Equal(t, "instance-val", attrVal.Str())
				}
			}
		})
	}
}
