// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

var MetricsInfo = metricsInfo{
	NfsMountOperationErrors: metricInfo{
		Name: "nfs.mount.operation.errors",
	},
	NfsMountOperationMajorTimeouts: metricInfo{
		Name: "nfs.mount.operation.major_timeouts",
	},
	NfsMountOperationReceivedBytes: metricInfo{
		Name: "nfs.mount.operation.received_bytes",
	},
	NfsMountOperationRequests: metricInfo{
		Name: "nfs.mount.operation.requests",
	},
	NfsMountOperationSentBytes: metricInfo{
		Name: "nfs.mount.operation.sent_bytes",
	},
	NfsMountOpsPerSecond: metricInfo{
		Name: "nfs.mount.ops_per_second",
	},
	NfsMountReadBytes: metricInfo{
		Name: "nfs.mount.read_bytes",
	},
	NfsMountReadExe: metricInfo{
		Name: "nfs.mount.read_exe",
	},
	NfsMountReadRtt: metricInfo{
		Name: "nfs.mount.read_rtt",
	},
	NfsMountRPCBacklog: metricInfo{
		Name: "nfs.mount.rpc_backlog",
	},
	NfsMountWriteBytes: metricInfo{
		Name: "nfs.mount.write_bytes",
	},
	NfsMountWriteExe: metricInfo{
		Name: "nfs.mount.write_exe",
	},
	NfsMountWriteRtt: metricInfo{
		Name: "nfs.mount.write_rtt",
	},
}

type metricsInfo struct {
	NfsMountOperationErrors        metricInfo
	NfsMountOperationMajorTimeouts metricInfo
	NfsMountOperationReceivedBytes metricInfo
	NfsMountOperationRequests      metricInfo
	NfsMountOperationSentBytes     metricInfo
	NfsMountOpsPerSecond           metricInfo
	NfsMountReadBytes              metricInfo
	NfsMountReadExe                metricInfo
	NfsMountReadRtt                metricInfo
	NfsMountRPCBacklog             metricInfo
	NfsMountWriteBytes             metricInfo
	NfsMountWriteExe               metricInfo
	NfsMountWriteRtt               metricInfo
}

type metricInfo struct {
	Name string
}

type metricNfsMountOperationErrors struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nfs.mount.operation.errors metric with initial data.
func (m *metricNfsMountOperationErrors) init() {
	m.data.SetName("nfs.mount.operation.errors")
	m.data.SetDescription("Number of requests that complete with tk_status < 0")
	m.data.SetUnit("{errors}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNfsMountOperationErrors) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, serverAttributeValue string, instanceAttributeValue string, operationAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("server", serverAttributeValue)
	dp.Attributes().PutStr("instance", instanceAttributeValue)
	dp.Attributes().PutStr("operation", operationAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsMountOperationErrors) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsMountOperationErrors) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsMountOperationErrors(cfg MetricConfig) metricNfsMountOperationErrors {
	m := metricNfsMountOperationErrors{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsMountOperationMajorTimeouts struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nfs.mount.operation.major_timeouts metric with initial data.
func (m *metricNfsMountOperationMajorTimeouts) init() {
	m.data.SetName("nfs.mount.operation.major_timeouts")
	m.data.SetDescription("Number of times a request has had a major timeout")
	m.data.SetUnit("{timeouts}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNfsMountOperationMajorTimeouts) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, serverAttributeValue string, instanceAttributeValue string, operationAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("server", serverAttributeValue)
	dp.Attributes().PutStr("instance", instanceAttributeValue)
	dp.Attributes().PutStr("operation", operationAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsMountOperationMajorTimeouts) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsMountOperationMajorTimeouts) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsMountOperationMajorTimeouts(cfg MetricConfig) metricNfsMountOperationMajorTimeouts {
	m := metricNfsMountOperationMajorTimeouts{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsMountOperationReceivedBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nfs.mount.operation.received_bytes metric with initial data.
func (m *metricNfsMountOperationReceivedBytes) init() {
	m.data.SetName("nfs.mount.operation.received_bytes")
	m.data.SetDescription("Total bytes received for these operations, including RPC headers and payload")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNfsMountOperationReceivedBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, serverAttributeValue string, instanceAttributeValue string, operationAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("server", serverAttributeValue)
	dp.Attributes().PutStr("instance", instanceAttributeValue)
	dp.Attributes().PutStr("operation", operationAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsMountOperationReceivedBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsMountOperationReceivedBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsMountOperationReceivedBytes(cfg MetricConfig) metricNfsMountOperationReceivedBytes {
	m := metricNfsMountOperationReceivedBytes{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsMountOperationRequests struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nfs.mount.operation.requests metric with initial data.
func (m *metricNfsMountOperationRequests) init() {
	m.data.SetName("nfs.mount.operation.requests")
	m.data.SetDescription("Number of requests")
	m.data.SetUnit("{requests}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNfsMountOperationRequests) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, serverAttributeValue string, instanceAttributeValue string, operationAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("server", serverAttributeValue)
	dp.Attributes().PutStr("instance", instanceAttributeValue)
	dp.Attributes().PutStr("operation", operationAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsMountOperationRequests) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsMountOperationRequests) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsMountOperationRequests(cfg MetricConfig) metricNfsMountOperationRequests {
	m := metricNfsMountOperationRequests{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsMountOperationSentBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nfs.mount.operation.sent_bytes metric with initial data.
func (m *metricNfsMountOperationSentBytes) init() {
	m.data.SetName("nfs.mount.operation.sent_bytes")
	m.data.SetDescription("Total bytes sent for these operations, including RPC headers and payload")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNfsMountOperationSentBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, serverAttributeValue string, instanceAttributeValue string, operationAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("server", serverAttributeValue)
	dp.Attributes().PutStr("instance", instanceAttributeValue)
	dp.Attributes().PutStr("operation", operationAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsMountOperationSentBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsMountOperationSentBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsMountOperationSentBytes(cfg MetricConfig) metricNfsMountOperationSentBytes {
	m := metricNfsMountOperationSentBytes{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsMountOpsPerSecond struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nfs.mount.ops_per_second metric with initial data.
func (m *metricNfsMountOpsPerSecond) init() {
	m.data.SetName("nfs.mount.ops_per_second")
	m.data.SetDescription("nfsiostat Mount Operations Per Second")
	m.data.SetUnit("{count}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNfsMountOpsPerSecond) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, serverAttributeValue string, instanceAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("server", serverAttributeValue)
	dp.Attributes().PutStr("instance", instanceAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsMountOpsPerSecond) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsMountOpsPerSecond) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsMountOpsPerSecond(cfg MetricConfig) metricNfsMountOpsPerSecond {
	m := metricNfsMountOpsPerSecond{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsMountReadBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nfs.mount.read_bytes metric with initial data.
func (m *metricNfsMountReadBytes) init() {
	m.data.SetName("nfs.mount.read_bytes")
	m.data.SetDescription("Bytes read from remote NFS server")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNfsMountReadBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, serverAttributeValue string, instanceAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("server", serverAttributeValue)
	dp.Attributes().PutStr("instance", instanceAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsMountReadBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsMountReadBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsMountReadBytes(cfg MetricConfig) metricNfsMountReadBytes {
	m := metricNfsMountReadBytes{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsMountReadExe struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nfs.mount.read_exe metric with initial data.
func (m *metricNfsMountReadExe) init() {
	m.data.SetName("nfs.mount.read_exe")
	m.data.SetDescription("nfsiostat Mount Read EXE")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNfsMountReadExe) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, serverAttributeValue string, instanceAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("server", serverAttributeValue)
	dp.Attributes().PutStr("instance", instanceAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsMountReadExe) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsMountReadExe) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsMountReadExe(cfg MetricConfig) metricNfsMountReadExe {
	m := metricNfsMountReadExe{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsMountReadRtt struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nfs.mount.read_rtt metric with initial data.
func (m *metricNfsMountReadRtt) init() {
	m.data.SetName("nfs.mount.read_rtt")
	m.data.SetDescription("nfsiostat Mount Read RTT")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNfsMountReadRtt) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, serverAttributeValue string, instanceAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("server", serverAttributeValue)
	dp.Attributes().PutStr("instance", instanceAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsMountReadRtt) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsMountReadRtt) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsMountReadRtt(cfg MetricConfig) metricNfsMountReadRtt {
	m := metricNfsMountReadRtt{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsMountRPCBacklog struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nfs.mount.rpc_backlog metric with initial data.
func (m *metricNfsMountRPCBacklog) init() {
	m.data.SetName("nfs.mount.rpc_backlog")
	m.data.SetDescription("nfsiostat Mount RPC Backlog")
	m.data.SetUnit("{count}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNfsMountRPCBacklog) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, serverAttributeValue string, instanceAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("server", serverAttributeValue)
	dp.Attributes().PutStr("instance", instanceAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsMountRPCBacklog) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsMountRPCBacklog) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsMountRPCBacklog(cfg MetricConfig) metricNfsMountRPCBacklog {
	m := metricNfsMountRPCBacklog{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsMountWriteBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nfs.mount.write_bytes metric with initial data.
func (m *metricNfsMountWriteBytes) init() {
	m.data.SetName("nfs.mount.write_bytes")
	m.data.SetDescription("Bytes wrote to remote NFS server")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNfsMountWriteBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, serverAttributeValue string, instanceAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("server", serverAttributeValue)
	dp.Attributes().PutStr("instance", instanceAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsMountWriteBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsMountWriteBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsMountWriteBytes(cfg MetricConfig) metricNfsMountWriteBytes {
	m := metricNfsMountWriteBytes{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsMountWriteExe struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nfs.mount.write_exe metric with initial data.
func (m *metricNfsMountWriteExe) init() {
	m.data.SetName("nfs.mount.write_exe")
	m.data.SetDescription("nfsiostat Mount Write EXE")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNfsMountWriteExe) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, serverAttributeValue string, instanceAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("server", serverAttributeValue)
	dp.Attributes().PutStr("instance", instanceAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsMountWriteExe) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsMountWriteExe) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsMountWriteExe(cfg MetricConfig) metricNfsMountWriteExe {
	m := metricNfsMountWriteExe{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsMountWriteRtt struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nfs.mount.write_rtt metric with initial data.
func (m *metricNfsMountWriteRtt) init() {
	m.data.SetName("nfs.mount.write_rtt")
	m.data.SetDescription("nfsiostat Mount Write RTT")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNfsMountWriteRtt) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, serverAttributeValue string, instanceAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("server", serverAttributeValue)
	dp.Attributes().PutStr("instance", instanceAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsMountWriteRtt) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsMountWriteRtt) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsMountWriteRtt(cfg MetricConfig) metricNfsMountWriteRtt {
	m := metricNfsMountWriteRtt{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                               MetricsBuilderConfig // config of the metrics builder.
	startTime                            pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                      int                  // maximum observed number of metrics per resource.
	metricsBuffer                        pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                            component.BuildInfo  // contains version information.
	metricNfsMountOperationErrors        metricNfsMountOperationErrors
	metricNfsMountOperationMajorTimeouts metricNfsMountOperationMajorTimeouts
	metricNfsMountOperationReceivedBytes metricNfsMountOperationReceivedBytes
	metricNfsMountOperationRequests      metricNfsMountOperationRequests
	metricNfsMountOperationSentBytes     metricNfsMountOperationSentBytes
	metricNfsMountOpsPerSecond           metricNfsMountOpsPerSecond
	metricNfsMountReadBytes              metricNfsMountReadBytes
	metricNfsMountReadExe                metricNfsMountReadExe
	metricNfsMountReadRtt                metricNfsMountReadRtt
	metricNfsMountRPCBacklog             metricNfsMountRPCBacklog
	metricNfsMountWriteBytes             metricNfsMountWriteBytes
	metricNfsMountWriteExe               metricNfsMountWriteExe
	metricNfsMountWriteRtt               metricNfsMountWriteRtt
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                               mbc,
		startTime:                            pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                        pmetric.NewMetrics(),
		buildInfo:                            settings.BuildInfo,
		metricNfsMountOperationErrors:        newMetricNfsMountOperationErrors(mbc.Metrics.NfsMountOperationErrors),
		metricNfsMountOperationMajorTimeouts: newMetricNfsMountOperationMajorTimeouts(mbc.Metrics.NfsMountOperationMajorTimeouts),
		metricNfsMountOperationReceivedBytes: newMetricNfsMountOperationReceivedBytes(mbc.Metrics.NfsMountOperationReceivedBytes),
		metricNfsMountOperationRequests:      newMetricNfsMountOperationRequests(mbc.Metrics.NfsMountOperationRequests),
		metricNfsMountOperationSentBytes:     newMetricNfsMountOperationSentBytes(mbc.Metrics.NfsMountOperationSentBytes),
		metricNfsMountOpsPerSecond:           newMetricNfsMountOpsPerSecond(mbc.Metrics.NfsMountOpsPerSecond),
		metricNfsMountReadBytes:              newMetricNfsMountReadBytes(mbc.Metrics.NfsMountReadBytes),
		metricNfsMountReadExe:                newMetricNfsMountReadExe(mbc.Metrics.NfsMountReadExe),
		metricNfsMountReadRtt:                newMetricNfsMountReadRtt(mbc.Metrics.NfsMountReadRtt),
		metricNfsMountRPCBacklog:             newMetricNfsMountRPCBacklog(mbc.Metrics.NfsMountRPCBacklog),
		metricNfsMountWriteBytes:             newMetricNfsMountWriteBytes(mbc.Metrics.NfsMountWriteBytes),
		metricNfsMountWriteExe:               newMetricNfsMountWriteExe(mbc.Metrics.NfsMountWriteExe),
		metricNfsMountWriteRtt:               newMetricNfsMountWriteRtt(mbc.Metrics.NfsMountWriteRtt),
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricNfsMountOperationErrors.emit(ils.Metrics())
	mb.metricNfsMountOperationMajorTimeouts.emit(ils.Metrics())
	mb.metricNfsMountOperationReceivedBytes.emit(ils.Metrics())
	mb.metricNfsMountOperationRequests.emit(ils.Metrics())
	mb.metricNfsMountOperationSentBytes.emit(ils.Metrics())
	mb.metricNfsMountOpsPerSecond.emit(ils.Metrics())
	mb.metricNfsMountReadBytes.emit(ils.Metrics())
	mb.metricNfsMountReadExe.emit(ils.Metrics())
	mb.metricNfsMountReadRtt.emit(ils.Metrics())
	mb.metricNfsMountRPCBacklog.emit(ils.Metrics())
	mb.metricNfsMountWriteBytes.emit(ils.Metrics())
	mb.metricNfsMountWriteExe.emit(ils.Metrics())
	mb.metricNfsMountWriteRtt.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordNfsMountOperationErrorsDataPoint adds a data point to nfs.mount.operation.errors metric.
func (mb *MetricsBuilder) RecordNfsMountOperationErrorsDataPoint(ts pcommon.Timestamp, val int64, serverAttributeValue string, instanceAttributeValue string, operationAttributeValue string) {
	mb.metricNfsMountOperationErrors.recordDataPoint(mb.startTime, ts, val, serverAttributeValue, instanceAttributeValue, operationAttributeValue)
}

// RecordNfsMountOperationMajorTimeoutsDataPoint adds a data point to nfs.mount.operation.major_timeouts metric.
func (mb *MetricsBuilder) RecordNfsMountOperationMajorTimeoutsDataPoint(ts pcommon.Timestamp, val int64, serverAttributeValue string, instanceAttributeValue string, operationAttributeValue string) {
	mb.metricNfsMountOperationMajorTimeouts.recordDataPoint(mb.startTime, ts, val, serverAttributeValue, instanceAttributeValue, operationAttributeValue)
}

// RecordNfsMountOperationReceivedBytesDataPoint adds a data point to nfs.mount.operation.received_bytes metric.
func (mb *MetricsBuilder) RecordNfsMountOperationReceivedBytesDataPoint(ts pcommon.Timestamp, val int64, serverAttributeValue string, instanceAttributeValue string, operationAttributeValue string) {
	mb.metricNfsMountOperationReceivedBytes.recordDataPoint(mb.startTime, ts, val, serverAttributeValue, instanceAttributeValue, operationAttributeValue)
}

// RecordNfsMountOperationRequestsDataPoint adds a data point to nfs.mount.operation.requests metric.
func (mb *MetricsBuilder) RecordNfsMountOperationRequestsDataPoint(ts pcommon.Timestamp, val int64, serverAttributeValue string, instanceAttributeValue string, operationAttributeValue string) {
	mb.metricNfsMountOperationRequests.recordDataPoint(mb.startTime, ts, val, serverAttributeValue, instanceAttributeValue, operationAttributeValue)
}

// RecordNfsMountOperationSentBytesDataPoint adds a data point to nfs.mount.operation.sent_bytes metric.
func (mb *MetricsBuilder) RecordNfsMountOperationSentBytesDataPoint(ts pcommon.Timestamp, val int64, serverAttributeValue string, instanceAttributeValue string, operationAttributeValue string) {
	mb.metricNfsMountOperationSentBytes.recordDataPoint(mb.startTime, ts, val, serverAttributeValue, instanceAttributeValue, operationAttributeValue)
}

// RecordNfsMountOpsPerSecondDataPoint adds a data point to nfs.mount.ops_per_second metric.
func (mb *MetricsBuilder) RecordNfsMountOpsPerSecondDataPoint(ts pcommon.Timestamp, val float64, serverAttributeValue string, instanceAttributeValue string) {
	mb.metricNfsMountOpsPerSecond.recordDataPoint(mb.startTime, ts, val, serverAttributeValue, instanceAttributeValue)
}

// RecordNfsMountReadBytesDataPoint adds a data point to nfs.mount.read_bytes metric.
func (mb *MetricsBuilder) RecordNfsMountReadBytesDataPoint(ts pcommon.Timestamp, val int64, serverAttributeValue string, instanceAttributeValue string) {
	mb.metricNfsMountReadBytes.recordDataPoint(mb.startTime, ts, val, serverAttributeValue, instanceAttributeValue)
}

// RecordNfsMountReadExeDataPoint adds a data point to nfs.mount.read_exe metric.
func (mb *MetricsBuilder) RecordNfsMountReadExeDataPoint(ts pcommon.Timestamp, val float64, serverAttributeValue string, instanceAttributeValue string) {
	mb.metricNfsMountReadExe.recordDataPoint(mb.startTime, ts, val, serverAttributeValue, instanceAttributeValue)
}

// RecordNfsMountReadRttDataPoint adds a data point to nfs.mount.read_rtt metric.
func (mb *MetricsBuilder) RecordNfsMountReadRttDataPoint(ts pcommon.Timestamp, val float64, serverAttributeValue string, instanceAttributeValue string) {
	mb.metricNfsMountReadRtt.recordDataPoint(mb.startTime, ts, val, serverAttributeValue, instanceAttributeValue)
}

// RecordNfsMountRPCBacklogDataPoint adds a data point to nfs.mount.rpc_backlog metric.
func (mb *MetricsBuilder) RecordNfsMountRPCBacklogDataPoint(ts pcommon.Timestamp, val float64, serverAttributeValue string, instanceAttributeValue string) {
	mb.metricNfsMountRPCBacklog.recordDataPoint(mb.startTime, ts, val, serverAttributeValue, instanceAttributeValue)
}

// RecordNfsMountWriteBytesDataPoint adds a data point to nfs.mount.write_bytes metric.
func (mb *MetricsBuilder) RecordNfsMountWriteBytesDataPoint(ts pcommon.Timestamp, val int64, serverAttributeValue string, instanceAttributeValue string) {
	mb.metricNfsMountWriteBytes.recordDataPoint(mb.startTime, ts, val, serverAttributeValue, instanceAttributeValue)
}

// RecordNfsMountWriteExeDataPoint adds a data point to nfs.mount.write_exe metric.
func (mb *MetricsBuilder) RecordNfsMountWriteExeDataPoint(ts pcommon.Timestamp, val float64, serverAttributeValue string, instanceAttributeValue string) {
	mb.metricNfsMountWriteExe.recordDataPoint(mb.startTime, ts, val, serverAttributeValue, instanceAttributeValue)
}

// RecordNfsMountWriteRttDataPoint adds a data point to nfs.mount.write_rtt metric.
func (mb *MetricsBuilder) RecordNfsMountWriteRttDataPoint(ts pcommon.Timestamp, val float64, serverAttributeValue string, instanceAttributeValue string) {
	mb.metricNfsMountWriteRtt.recordDataPoint(mb.startTime, ts, val, serverAttributeValue, instanceAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
