// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for mounts metrics.
type MetricsConfig struct {
	NfsMountOperationErrors        MetricConfig `mapstructure:"nfs.mount.operation.errors"`
	NfsMountOperationMajorTimeouts MetricConfig `mapstructure:"nfs.mount.operation.major_timeouts"`
	NfsMountOperationReceivedBytes MetricConfig `mapstructure:"nfs.mount.operation.received_bytes"`
	NfsMountOperationRequests      MetricConfig `mapstructure:"nfs.mount.operation.requests"`
	NfsMountOperationSentBytes     MetricConfig `mapstructure:"nfs.mount.operation.sent_bytes"`
	NfsMountOpsPerSecond           MetricConfig `mapstructure:"nfs.mount.ops_per_second"`
	NfsMountReadBytes              MetricConfig `mapstructure:"nfs.mount.read_bytes"`
	NfsMountReadExe                MetricConfig `mapstructure:"nfs.mount.read_exe"`
	NfsMountReadRtt                MetricConfig `mapstructure:"nfs.mount.read_rtt"`
	NfsMountRPCBacklog             MetricConfig `mapstructure:"nfs.mount.rpc_backlog"`
	NfsMountWriteBytes             MetricConfig `mapstructure:"nfs.mount.write_bytes"`
	NfsMountWriteExe               MetricConfig `mapstructure:"nfs.mount.write_exe"`
	NfsMountWriteRtt               MetricConfig `mapstructure:"nfs.mount.write_rtt"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		NfsMountOperationErrors: MetricConfig{
			Enabled: true,
		},
		NfsMountOperationMajorTimeouts: MetricConfig{
			Enabled: true,
		},
		NfsMountOperationReceivedBytes: MetricConfig{
			Enabled: true,
		},
		NfsMountOperationRequests: MetricConfig{
			Enabled: true,
		},
		NfsMountOperationSentBytes: MetricConfig{
			Enabled: true,
		},
		NfsMountOpsPerSecond: MetricConfig{
			Enabled: true,
		},
		NfsMountReadBytes: MetricConfig{
			Enabled: true,
		},
		NfsMountReadExe: MetricConfig{
			Enabled: true,
		},
		NfsMountReadRtt: MetricConfig{
			Enabled: true,
		},
		NfsMountRPCBacklog: MetricConfig{
			Enabled: true,
		},
		NfsMountWriteBytes: MetricConfig{
			Enabled: true,
		},
		NfsMountWriteExe: MetricConfig{
			Enabled: true,
		},
		NfsMountWriteRtt: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for mounts metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
