// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					NfsMountOperationErrors: NfsMountOperationErrorsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []NfsMountOperationErrorsMetricAttributeKey{NfsMountOperationErrorsMetricAttributeKeyServer, NfsMountOperationErrorsMetricAttributeKeyInstance, NfsMountOperationErrorsMetricAttributeKeyOperation},
					},
					NfsMountOperationMajorTimeouts: NfsMountOperationMajorTimeoutsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []NfsMountOperationMajorTimeoutsMetricAttributeKey{NfsMountOperationMajorTimeoutsMetricAttributeKeyServer, NfsMountOperationMajorTimeoutsMetricAttributeKeyInstance, NfsMountOperationMajorTimeoutsMetricAttributeKeyOperation},
					},
					NfsMountOperationReceivedBytes: NfsMountOperationReceivedBytesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []NfsMountOperationReceivedBytesMetricAttributeKey{NfsMountOperationReceivedBytesMetricAttributeKeyServer, NfsMountOperationReceivedBytesMetricAttributeKeyInstance, NfsMountOperationReceivedBytesMetricAttributeKeyOperation},
					},
					NfsMountOperationRequests: NfsMountOperationRequestsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []NfsMountOperationRequestsMetricAttributeKey{NfsMountOperationRequestsMetricAttributeKeyServer, NfsMountOperationRequestsMetricAttributeKeyInstance, NfsMountOperationRequestsMetricAttributeKeyOperation},
					},
					NfsMountOperationSentBytes: NfsMountOperationSentBytesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []NfsMountOperationSentBytesMetricAttributeKey{NfsMountOperationSentBytesMetricAttributeKeyServer, NfsMountOperationSentBytesMetricAttributeKeyInstance, NfsMountOperationSentBytesMetricAttributeKeyOperation},
					},
					NfsMountOpsPerSecond: NfsMountOpsPerSecondMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []NfsMountOpsPerSecondMetricAttributeKey{NfsMountOpsPerSecondMetricAttributeKeyServer, NfsMountOpsPerSecondMetricAttributeKeyInstance},
					},
					NfsMountReadBytes: NfsMountReadBytesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []NfsMountReadBytesMetricAttributeKey{NfsMountReadBytesMetricAttributeKeyServer, NfsMountReadBytesMetricAttributeKeyInstance},
					},
					NfsMountReadExe: NfsMountReadExeMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []NfsMountReadExeMetricAttributeKey{NfsMountReadExeMetricAttributeKeyServer, NfsMountReadExeMetricAttributeKeyInstance},
					},
					NfsMountReadRtt: NfsMountReadRttMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []NfsMountReadRttMetricAttributeKey{NfsMountReadRttMetricAttributeKeyServer, NfsMountReadRttMetricAttributeKeyInstance},
					},
					NfsMountRPCBacklog: NfsMountRPCBacklogMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []NfsMountRPCBacklogMetricAttributeKey{NfsMountRPCBacklogMetricAttributeKeyServer, NfsMountRPCBacklogMetricAttributeKeyInstance},
					},
					NfsMountWriteBytes: NfsMountWriteBytesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []NfsMountWriteBytesMetricAttributeKey{NfsMountWriteBytesMetricAttributeKeyServer, NfsMountWriteBytesMetricAttributeKeyInstance},
					},
					NfsMountWriteExe: NfsMountWriteExeMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []NfsMountWriteExeMetricAttributeKey{NfsMountWriteExeMetricAttributeKeyServer, NfsMountWriteExeMetricAttributeKeyInstance},
					},
					NfsMountWriteRtt: NfsMountWriteRttMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []NfsMountWriteRttMetricAttributeKey{NfsMountWriteRttMetricAttributeKeyServer, NfsMountWriteRttMetricAttributeKeyInstance},
					},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					NfsMountOperationErrors: NfsMountOperationErrorsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []NfsMountOperationErrorsMetricAttributeKey{NfsMountOperationErrorsMetricAttributeKeyServer, NfsMountOperationErrorsMetricAttributeKeyInstance, NfsMountOperationErrorsMetricAttributeKeyOperation},
					},
					NfsMountOperationMajorTimeouts: NfsMountOperationMajorTimeoutsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []NfsMountOperationMajorTimeoutsMetricAttributeKey{NfsMountOperationMajorTimeoutsMetricAttributeKeyServer, NfsMountOperationMajorTimeoutsMetricAttributeKeyInstance, NfsMountOperationMajorTimeoutsMetricAttributeKeyOperation},
					},
					NfsMountOperationReceivedBytes: NfsMountOperationReceivedBytesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []NfsMountOperationReceivedBytesMetricAttributeKey{NfsMountOperationReceivedBytesMetricAttributeKeyServer, NfsMountOperationReceivedBytesMetricAttributeKeyInstance, NfsMountOperationReceivedBytesMetricAttributeKeyOperation},
					},
					NfsMountOperationRequests: NfsMountOperationRequestsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []NfsMountOperationRequestsMetricAttributeKey{NfsMountOperationRequestsMetricAttributeKeyServer, NfsMountOperationRequestsMetricAttributeKeyInstance, NfsMountOperationRequestsMetricAttributeKeyOperation},
					},
					NfsMountOperationSentBytes: NfsMountOperationSentBytesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []NfsMountOperationSentBytesMetricAttributeKey{NfsMountOperationSentBytesMetricAttributeKeyServer, NfsMountOperationSentBytesMetricAttributeKeyInstance, NfsMountOperationSentBytesMetricAttributeKeyOperation},
					},
					NfsMountOpsPerSecond: NfsMountOpsPerSecondMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []NfsMountOpsPerSecondMetricAttributeKey{NfsMountOpsPerSecondMetricAttributeKeyServer, NfsMountOpsPerSecondMetricAttributeKeyInstance},
					},
					NfsMountReadBytes: NfsMountReadBytesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []NfsMountReadBytesMetricAttributeKey{NfsMountReadBytesMetricAttributeKeyServer, NfsMountReadBytesMetricAttributeKeyInstance},
					},
					NfsMountReadExe: NfsMountReadExeMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []NfsMountReadExeMetricAttributeKey{NfsMountReadExeMetricAttributeKeyServer, NfsMountReadExeMetricAttributeKeyInstance},
					},
					NfsMountReadRtt: NfsMountReadRttMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []NfsMountReadRttMetricAttributeKey{NfsMountReadRttMetricAttributeKeyServer, NfsMountReadRttMetricAttributeKeyInstance},
					},
					NfsMountRPCBacklog: NfsMountRPCBacklogMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []NfsMountRPCBacklogMetricAttributeKey{NfsMountRPCBacklogMetricAttributeKeyServer, NfsMountRPCBacklogMetricAttributeKeyInstance},
					},
					NfsMountWriteBytes: NfsMountWriteBytesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []NfsMountWriteBytesMetricAttributeKey{NfsMountWriteBytesMetricAttributeKeyServer, NfsMountWriteBytesMetricAttributeKeyInstance},
					},
					NfsMountWriteExe: NfsMountWriteExeMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []NfsMountWriteExeMetricAttributeKey{NfsMountWriteExeMetricAttributeKeyServer, NfsMountWriteExeMetricAttributeKeyInstance},
					},
					NfsMountWriteRtt: NfsMountWriteRttMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []NfsMountWriteRttMetricAttributeKey{NfsMountWriteRttMetricAttributeKeyServer, NfsMountWriteRttMetricAttributeKeyInstance},
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(NfsMountOperationErrorsMetricConfig{}, NfsMountOperationMajorTimeoutsMetricConfig{}, NfsMountOperationReceivedBytesMetricConfig{}, NfsMountOperationRequestsMetricConfig{}, NfsMountOperationSentBytesMetricConfig{}, NfsMountOpsPerSecondMetricConfig{}, NfsMountReadBytesMetricConfig{}, NfsMountReadExeMetricConfig{}, NfsMountReadRttMetricConfig{}, NfsMountRPCBacklogMetricConfig{}, NfsMountWriteBytesMetricConfig{}, NfsMountWriteExeMetricConfig{}, NfsMountWriteRttMetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}
func TestNfsMountOperationErrorsMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().NfsMountOperationErrors
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []NfsMountOperationErrorsMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric nfs.mount.operation.errors doesn't have an attribute invalid, valid attributes: [server, instance, operation]")

	cfg = DefaultMetricsConfig().NfsMountOperationErrors
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestNfsMountOperationMajorTimeoutsMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().NfsMountOperationMajorTimeouts
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []NfsMountOperationMajorTimeoutsMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric nfs.mount.operation.major_timeouts doesn't have an attribute invalid, valid attributes: [server, instance, operation]")

	cfg = DefaultMetricsConfig().NfsMountOperationMajorTimeouts
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestNfsMountOperationReceivedBytesMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().NfsMountOperationReceivedBytes
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []NfsMountOperationReceivedBytesMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric nfs.mount.operation.received_bytes doesn't have an attribute invalid, valid attributes: [server, instance, operation]")

	cfg = DefaultMetricsConfig().NfsMountOperationReceivedBytes
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestNfsMountOperationRequestsMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().NfsMountOperationRequests
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []NfsMountOperationRequestsMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric nfs.mount.operation.requests doesn't have an attribute invalid, valid attributes: [server, instance, operation]")

	cfg = DefaultMetricsConfig().NfsMountOperationRequests
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestNfsMountOperationSentBytesMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().NfsMountOperationSentBytes
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []NfsMountOperationSentBytesMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric nfs.mount.operation.sent_bytes doesn't have an attribute invalid, valid attributes: [server, instance, operation]")

	cfg = DefaultMetricsConfig().NfsMountOperationSentBytes
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestNfsMountOpsPerSecondMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().NfsMountOpsPerSecond
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []NfsMountOpsPerSecondMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric nfs.mount.ops_per_second doesn't have an attribute invalid, valid attributes: [server, instance]")

	cfg = DefaultMetricsConfig().NfsMountOpsPerSecond
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestNfsMountReadBytesMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().NfsMountReadBytes
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []NfsMountReadBytesMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric nfs.mount.read_bytes doesn't have an attribute invalid, valid attributes: [server, instance]")

	cfg = DefaultMetricsConfig().NfsMountReadBytes
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestNfsMountReadExeMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().NfsMountReadExe
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []NfsMountReadExeMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric nfs.mount.read_exe doesn't have an attribute invalid, valid attributes: [server, instance]")

	cfg = DefaultMetricsConfig().NfsMountReadExe
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestNfsMountReadRttMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().NfsMountReadRtt
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []NfsMountReadRttMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric nfs.mount.read_rtt doesn't have an attribute invalid, valid attributes: [server, instance]")

	cfg = DefaultMetricsConfig().NfsMountReadRtt
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestNfsMountRPCBacklogMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().NfsMountRPCBacklog
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []NfsMountRPCBacklogMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric nfs.mount.rpc_backlog doesn't have an attribute invalid, valid attributes: [server, instance]")

	cfg = DefaultMetricsConfig().NfsMountRPCBacklog
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestNfsMountWriteBytesMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().NfsMountWriteBytes
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []NfsMountWriteBytesMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric nfs.mount.write_bytes doesn't have an attribute invalid, valid attributes: [server, instance]")

	cfg = DefaultMetricsConfig().NfsMountWriteBytes
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestNfsMountWriteExeMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().NfsMountWriteExe
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []NfsMountWriteExeMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric nfs.mount.write_exe doesn't have an attribute invalid, valid attributes: [server, instance]")

	cfg = DefaultMetricsConfig().NfsMountWriteExe
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestNfsMountWriteRttMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().NfsMountWriteRtt
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []NfsMountWriteRttMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric nfs.mount.write_rtt doesn't have an attribute invalid, valid attributes: [server, instance]")

	cfg = DefaultMetricsConfig().NfsMountWriteRtt
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
