# Copyright 2022 Google LLC
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

receivers:
  mounts:
    query_proxy_instance:
      # When enabled the collector will query the "/api/v1/nodeInfo" endpoint
      # for each NFS server that is mounted so that the client can report the
      # instance name of the knfsd proxy that the client is connected to.
      enabled: true
      timeout: 10s
      # # If the client is mounting some servers directly (i.e. not via a knfsd
      # # proxy) list the servers or local mount paths to exclude from querying.
      # exclude:
      #   # Exclude specific servers. This must match the name or IP used when
      #   # mounting the export.
      #   servers:
      #   - logs.example
      #   # Exclude specific servers based upon the local path where the export
      #   # is mounted. If the client mounts multiple exports from the same server
      #   # then the server will be excluded if any path matches.
      #   local_paths:
      #   - /mnt/logs

exporters:
  awsemf:
    metric_declarations:
      # per-mount metrics
      - dimensions:
          - [InstanceId, server, instance]
        metric_name_selectors:
          - "^knfsd/nfsiostat_.+"
          - "^knfsd/mount/(read_bytes|write_bytes)$"

      # per-mount operation metrics
      - dimensions:
          - [InstanceId, server, instance, operation]
        metric_name_selectors:
          - "^knfsd/mount/operation/.+"

service:
  pipelines:
    metrics:
      receivers: [mounts, slabinfo]
      processors: [resourcedetection, transform, metricstransform]
      exporters: [awsemf]
