# Copyright 2022 Google LLC
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "/run/knfsd-metrics.sock"
        transport: "unix"

exporters:
  awsemf:
    metric_declarations:
      # proxy-level metrics
      - dimensions:
          - [AutoScalingGroupName, InstanceId]
        metric_name_selectors:
          - "^knfsd/nfs_.+"
          - "^knfsd/dentry_.+"
          - "^knfsd/exports/.+"
          - "^knfsd/fscache/.+"
          - "^knfsd/netfs/.+"
          - "^knfsd/fsid/.+"

      # per-mount metrics
      - dimensions:
          - [AutoScalingGroupName, InstanceId, server]
        metric_name_selectors:
          - "^knfsd/nfsiostat_.+"
          - "^knfsd/mount/(read_bytes|write_bytes)$"

      # per-mount operation metrics
      - dimensions:
          - [AutoScalingGroupName, InstanceId, server, operation]
        metric_name_selectors:
          - "^knfsd/mount/operation/.+"

      # fsid operation metrics
      - dimensions:
          - [AutoScalingGroupName, InstanceId, command, result, retry]
        metric_name_selectors:
          - "^knfsd/fsid/operation/.+"

      # fsid request metrics
      - dimensions:
          - [AutoScalingGroupName, InstanceId, command, result]
        metric_name_selectors:
          - "^knfsd/fsid/request/.+"

      # fsid sql query metrics
      - dimensions:
          - [AutoScalingGroupName, InstanceId, query, result]
        metric_name_selectors:
          - "^knfsd/fsid/sql/query/.+"

service:
  pipelines:
    metrics:
      receivers: [otlp, connections, mounts, nfsd, fscache, exports, slabinfo]
      processors: [memory_limiter, resourcedetection, transform, metrics_transform]
      exporters: [awsemf]
