# Start Postgres using docker compose so that we can wait until the container
# is healthy.
name: db-postgres
services:
  postgres:
    image: postgres:18.4-alpine3.23
    platform: linux/amd64
    healthcheck:
      test: "pg_isready --host=127.0.0.1 --username=\"$$POSTGRES_USER\" --dbname=\"$$POSTGRES_DB\""
      interval: 5s
      timeout: 15s
      retries: 6
      start_period: 5m
    ports:
      - target: 5432
        host_ip: 127.0.0.1
        published: ${POSTGRES_PORT:-0}
    environment:
      POSTGRES_PASSWORD: fsid-test
      POSTGRES_USER: fsidd
      POSTGRES_DB: fsids
    cap_drop:
      - ALL
    cap_add:
      - CAP_SETGID
      - CAP_SETUID
      - CAP_CHOWN
      - CAP_FOWNER
    security_opt:
      - no-new-privileges:true
