// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("oldestfile")
	ScopeName = "knfsd-metrics-agent/oldestfile"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
