// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// FscacheOldestFileMetricConfig provides config for the fscache.oldest_file metric.
type FscacheOldestFileMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *FscacheOldestFileMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for oldestfile metrics.
type MetricsConfig struct {
	FscacheOldestFile FscacheOldestFileMetricConfig `mapstructure:"fscache.oldest_file"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		FscacheOldestFile: FscacheOldestFileMetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for oldestfile metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
