// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
	"time"
)

const (
	AggregationStrategySum = "sum"
	AggregationStrategyAvg = "avg"
	AggregationStrategyMin = "min"
	AggregationStrategyMax = "max"
)

var MetricsInfo = metricsInfo{
	FscacheExtentsMax: metricInfo{
		Name: "fscache.extents.max",
	},
	FscacheExtentsMeanBytes: metricInfo{
		Name: "fscache.extents.mean_bytes",
	},
	FscacheExtentsUnwrittenBytes: metricInfo{
		Name: "fscache.extents.unwritten_bytes",
	},
	FscacheFragmentationScrapeDuration: metricInfo{
		Name: "fscache.fragmentation.scrape_duration",
	},
}

type metricsInfo struct {
	FscacheExtentsMax                  metricInfo
	FscacheExtentsMeanBytes            metricInfo
	FscacheExtentsUnwrittenBytes       metricInfo
	FscacheFragmentationScrapeDuration metricInfo
}

type metricInfo struct {
	Name       string
	Attributes []string
}

type metricFscacheExtentsMax struct {
	data     pmetric.Metric                // data buffer for generated metric.
	config   FscacheExtentsMaxMetricConfig // metric config provided by user.
	capacity int                           // max observed number of data points added to the metric.
}

// init fills fscache.extents.max metric with initial data.
func (m *metricFscacheExtentsMax) init() {
	m.data.SetName("fscache.extents.max")
	m.data.SetDescription("Highest extent count of any single FS-Cache backing file. SEEK_HOLE cost in the cachefiles read path is proportional to this value.")
	m.data.SetUnit("{extents}")
	m.data.SetEmptyGauge()
}

func (m *metricFscacheExtentsMax) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFscacheExtentsMax) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFscacheExtentsMax) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFscacheExtentsMax(cfg FscacheExtentsMaxMetricConfig) metricFscacheExtentsMax {
	m := metricFscacheExtentsMax{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricFscacheExtentsMeanBytes struct {
	data     pmetric.Metric                      // data buffer for generated metric.
	config   FscacheExtentsMeanBytesMetricConfig // metric config provided by user.
	capacity int                                 // max observed number of data points added to the metric.
}

// init fills fscache.extents.mean_bytes metric with initial data.
func (m *metricFscacheExtentsMeanBytes) init() {
	m.data.SetName("fscache.extents.mean_bytes")
	m.data.SetDescription("Mean extent length across all FS-Cache backing files. A value below the NFS rsize indicates cache writes are not coalescing into larger extents.")
	m.data.SetUnit("By")
	m.data.SetEmptyGauge()
}

func (m *metricFscacheExtentsMeanBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFscacheExtentsMeanBytes) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFscacheExtentsMeanBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFscacheExtentsMeanBytes(cfg FscacheExtentsMeanBytesMetricConfig) metricFscacheExtentsMeanBytes {
	m := metricFscacheExtentsMeanBytes{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricFscacheExtentsUnwrittenBytes struct {
	data     pmetric.Metric                           // data buffer for generated metric.
	config   FscacheExtentsUnwrittenBytesMetricConfig // metric config provided by user.
	capacity int                                      // max observed number of data points added to the metric.
}

// init fills fscache.extents.unwritten_bytes metric with initial data.
func (m *metricFscacheExtentsUnwrittenBytes) init() {
	m.data.SetName("fscache.extents.unwritten_bytes")
	m.data.SetDescription("Disk capacity allocated to FS-Cache backing files in unwritten extents, holding no cached data yet. XFS pads each allocation up to the extent size hint and marks the surplus unwritten, so this is the capacity CACHEFILESD_EXTSIZE has reserved ahead of use. Consumed as backing files fill. Zero when the hint is disabled.")
	m.data.SetUnit("By")
	m.data.SetEmptyGauge()
}

func (m *metricFscacheExtentsUnwrittenBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFscacheExtentsUnwrittenBytes) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFscacheExtentsUnwrittenBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFscacheExtentsUnwrittenBytes(cfg FscacheExtentsUnwrittenBytesMetricConfig) metricFscacheExtentsUnwrittenBytes {
	m := metricFscacheExtentsUnwrittenBytes{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricFscacheFragmentationScrapeDuration struct {
	data     pmetric.Metric                                 // data buffer for generated metric.
	config   FscacheFragmentationScrapeDurationMetricConfig // metric config provided by user.
	capacity int                                            // max observed number of data points added to the metric.
}

// init fills fscache.fragmentation.scrape_duration metric with initial data.
func (m *metricFscacheFragmentationScrapeDuration) init() {
	m.data.SetName("fscache.fragmentation.scrape_duration")
	m.data.SetDescription("Time taken to scan FS-Cache and collect extent statistics. Use this to tune the collection_interval; keep the duration well below the interval.")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
}

func (m *metricFscacheFragmentationScrapeDuration) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFscacheFragmentationScrapeDuration) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFscacheFragmentationScrapeDuration) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFscacheFragmentationScrapeDuration(cfg FscacheFragmentationScrapeDurationMetricConfig) metricFscacheFragmentationScrapeDuration {
	m := metricFscacheFragmentationScrapeDuration{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                                   MetricsBuilderConfig // config of the metrics builder.
	startTime                                pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                          int                  // maximum observed number of metrics per resource.
	metricsBuffer                            pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                                component.BuildInfo  // contains version information.
	metricFscacheExtentsMax                  metricFscacheExtentsMax
	metricFscacheExtentsMeanBytes            metricFscacheExtentsMeanBytes
	metricFscacheExtentsUnwrittenBytes       metricFscacheExtentsUnwrittenBytes
	metricFscacheFragmentationScrapeDuration metricFscacheFragmentationScrapeDuration
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                                   mbc,
		startTime:                                pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                            pmetric.NewMetrics(),
		buildInfo:                                settings.BuildInfo,
		metricFscacheExtentsMax:                  newMetricFscacheExtentsMax(mbc.Metrics.FscacheExtentsMax),
		metricFscacheExtentsMeanBytes:            newMetricFscacheExtentsMeanBytes(mbc.Metrics.FscacheExtentsMeanBytes),
		metricFscacheExtentsUnwrittenBytes:       newMetricFscacheExtentsUnwrittenBytes(mbc.Metrics.FscacheExtentsUnwrittenBytes),
		metricFscacheFragmentationScrapeDuration: newMetricFscacheFragmentationScrapeDuration(mbc.Metrics.FscacheFragmentationScrapeDuration),
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricFscacheExtentsMax.emit(ils.Metrics())
	mb.metricFscacheExtentsMeanBytes.emit(ils.Metrics())
	mb.metricFscacheExtentsUnwrittenBytes.emit(ils.Metrics())
	mb.metricFscacheFragmentationScrapeDuration.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordFscacheExtentsMaxDataPoint adds a data point to fscache.extents.max metric.
func (mb *MetricsBuilder) RecordFscacheExtentsMaxDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricFscacheExtentsMax.recordDataPoint(mb.startTime, ts, val)
}

// RecordFscacheExtentsMeanBytesDataPoint adds a data point to fscache.extents.mean_bytes metric.
func (mb *MetricsBuilder) RecordFscacheExtentsMeanBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricFscacheExtentsMeanBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordFscacheExtentsUnwrittenBytesDataPoint adds a data point to fscache.extents.unwritten_bytes metric.
func (mb *MetricsBuilder) RecordFscacheExtentsUnwrittenBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricFscacheExtentsUnwrittenBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordFscacheFragmentationScrapeDurationDataPoint adds a data point to fscache.fragmentation.scrape_duration metric.
func (mb *MetricsBuilder) RecordFscacheFragmentationScrapeDurationDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricFscacheFragmentationScrapeDuration.recordDataPoint(mb.startTime, ts, val)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
