// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// FscacheExtentsMaxMetricConfig provides config for the fscache.extents.max metric.
type FscacheExtentsMaxMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *FscacheExtentsMaxMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// FscacheExtentsMeanBytesMetricConfig provides config for the fscache.extents.mean_bytes metric.
type FscacheExtentsMeanBytesMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *FscacheExtentsMeanBytesMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// FscacheExtentsUnwrittenBytesMetricConfig provides config for the fscache.extents.unwritten_bytes metric.
type FscacheExtentsUnwrittenBytesMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *FscacheExtentsUnwrittenBytesMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// FscacheFragmentationScrapeDurationMetricConfig provides config for the fscache.fragmentation.scrape_duration metric.
type FscacheFragmentationScrapeDurationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *FscacheFragmentationScrapeDurationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for fragmentation metrics.
type MetricsConfig struct {
	FscacheExtentsMax                  FscacheExtentsMaxMetricConfig                  `mapstructure:"fscache.extents.max"`
	FscacheExtentsMeanBytes            FscacheExtentsMeanBytesMetricConfig            `mapstructure:"fscache.extents.mean_bytes"`
	FscacheExtentsUnwrittenBytes       FscacheExtentsUnwrittenBytesMetricConfig       `mapstructure:"fscache.extents.unwritten_bytes"`
	FscacheFragmentationScrapeDuration FscacheFragmentationScrapeDurationMetricConfig `mapstructure:"fscache.fragmentation.scrape_duration"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		FscacheExtentsMax: FscacheExtentsMaxMetricConfig{
			Enabled: true,
		},
		FscacheExtentsMeanBytes: FscacheExtentsMeanBytesMetricConfig{
			Enabled: true,
		},
		FscacheExtentsUnwrittenBytes: FscacheExtentsUnwrittenBytesMetricConfig{
			Enabled: true,
		},
		FscacheFragmentationScrapeDuration: FscacheFragmentationScrapeDurationMetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for fragmentation metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
