// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/fragmentation component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("fragmentation")
	ScopeName = "knfsd-metrics-agent/fragmentation"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
