// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("slabinfo")
	ScopeName = "knfsd-metrics-agent/slabinfo"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
