// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/slabinfo component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("slabinfo")
	ScopeName = "knfsd-metrics-agent/slabinfo"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
