// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// SlabDentryCacheActiveObjectsMetricConfig provides config for the slab.dentry_cache.active_objects metric.
type SlabDentryCacheActiveObjectsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SlabDentryCacheActiveObjectsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SlabDentryCacheObjsizeMetricConfig provides config for the slab.dentry_cache.objsize metric.
type SlabDentryCacheObjsizeMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SlabDentryCacheObjsizeMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SlabNfsInodeCacheActiveObjectsMetricConfig provides config for the slab.nfs_inode_cache.active_objects metric.
type SlabNfsInodeCacheActiveObjectsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SlabNfsInodeCacheActiveObjectsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SlabNfsInodeCacheObjsizeMetricConfig provides config for the slab.nfs_inode_cache.objsize metric.
type SlabNfsInodeCacheObjsizeMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SlabNfsInodeCacheObjsizeMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for slabinfo metrics.
type MetricsConfig struct {
	SlabDentryCacheActiveObjects   SlabDentryCacheActiveObjectsMetricConfig   `mapstructure:"slab.dentry_cache.active_objects"`
	SlabDentryCacheObjsize         SlabDentryCacheObjsizeMetricConfig         `mapstructure:"slab.dentry_cache.objsize"`
	SlabNfsInodeCacheActiveObjects SlabNfsInodeCacheActiveObjectsMetricConfig `mapstructure:"slab.nfs_inode_cache.active_objects"`
	SlabNfsInodeCacheObjsize       SlabNfsInodeCacheObjsizeMetricConfig       `mapstructure:"slab.nfs_inode_cache.objsize"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		SlabDentryCacheActiveObjects: SlabDentryCacheActiveObjectsMetricConfig{
			Enabled: true,
		},
		SlabDentryCacheObjsize: SlabDentryCacheObjsizeMetricConfig{
			Enabled: true,
		},
		SlabNfsInodeCacheActiveObjects: SlabNfsInodeCacheActiveObjectsMetricConfig{
			Enabled: true,
		},
		SlabNfsInodeCacheObjsize: SlabNfsInodeCacheObjsizeMetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for slabinfo metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
