// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for slabinfo metrics.
type MetricsConfig struct {
	SlabDentryCacheActiveObjects   MetricConfig `mapstructure:"slab.dentry_cache.active_objects"`
	SlabDentryCacheObjsize         MetricConfig `mapstructure:"slab.dentry_cache.objsize"`
	SlabNfsInodeCacheActiveObjects MetricConfig `mapstructure:"slab.nfs_inode_cache.active_objects"`
	SlabNfsInodeCacheObjsize       MetricConfig `mapstructure:"slab.nfs_inode_cache.objsize"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		SlabDentryCacheActiveObjects: MetricConfig{
			Enabled: true,
		},
		SlabDentryCacheObjsize: MetricConfig{
			Enabled: true,
		},
		SlabNfsInodeCacheActiveObjects: MetricConfig{
			Enabled: true,
		},
		SlabNfsInodeCacheObjsize: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for slabinfo metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
