// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
	"time"
)

const (
	AggregationStrategySum = "sum"
	AggregationStrategyAvg = "avg"
	AggregationStrategyMin = "min"
	AggregationStrategyMax = "max"
)

var MetricsInfo = metricsInfo{
	SlabDentryCacheActiveObjects: metricInfo{
		Name: "slab.dentry_cache.active_objects",
	},
	SlabDentryCacheObjsize: metricInfo{
		Name: "slab.dentry_cache.objsize",
	},
	SlabNfsInodeCacheActiveObjects: metricInfo{
		Name: "slab.nfs_inode_cache.active_objects",
	},
	SlabNfsInodeCacheObjsize: metricInfo{
		Name: "slab.nfs_inode_cache.objsize",
	},
}

type metricsInfo struct {
	SlabDentryCacheActiveObjects   metricInfo
	SlabDentryCacheObjsize         metricInfo
	SlabNfsInodeCacheActiveObjects metricInfo
	SlabNfsInodeCacheObjsize       metricInfo
}

type metricInfo struct {
	Name       string
	Attributes []string
}

type metricSlabDentryCacheActiveObjects struct {
	data     pmetric.Metric                           // data buffer for generated metric.
	config   SlabDentryCacheActiveObjectsMetricConfig // metric config provided by user.
	capacity int                                      // max observed number of data points added to the metric.
}

// init fills slab.dentry_cache.active_objects metric with initial data.
func (m *metricSlabDentryCacheActiveObjects) init() {
	m.data.SetName("slab.dentry_cache.active_objects")
	m.data.SetDescription("Dentry Cache Active Objects")
	m.data.SetUnit("{count}")
	m.data.SetEmptyGauge()
}

func (m *metricSlabDentryCacheActiveObjects) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricSlabDentryCacheActiveObjects) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricSlabDentryCacheActiveObjects) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricSlabDentryCacheActiveObjects(cfg SlabDentryCacheActiveObjectsMetricConfig) metricSlabDentryCacheActiveObjects {
	m := metricSlabDentryCacheActiveObjects{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricSlabDentryCacheObjsize struct {
	data     pmetric.Metric                     // data buffer for generated metric.
	config   SlabDentryCacheObjsizeMetricConfig // metric config provided by user.
	capacity int                                // max observed number of data points added to the metric.
}

// init fills slab.dentry_cache.objsize metric with initial data.
func (m *metricSlabDentryCacheObjsize) init() {
	m.data.SetName("slab.dentry_cache.objsize")
	m.data.SetDescription("Dentry Cache Object Size")
	m.data.SetUnit("{size}")
	m.data.SetEmptyGauge()
}

func (m *metricSlabDentryCacheObjsize) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricSlabDentryCacheObjsize) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricSlabDentryCacheObjsize) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricSlabDentryCacheObjsize(cfg SlabDentryCacheObjsizeMetricConfig) metricSlabDentryCacheObjsize {
	m := metricSlabDentryCacheObjsize{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricSlabNfsInodeCacheActiveObjects struct {
	data     pmetric.Metric                             // data buffer for generated metric.
	config   SlabNfsInodeCacheActiveObjectsMetricConfig // metric config provided by user.
	capacity int                                        // max observed number of data points added to the metric.
}

// init fills slab.nfs_inode_cache.active_objects metric with initial data.
func (m *metricSlabNfsInodeCacheActiveObjects) init() {
	m.data.SetName("slab.nfs_inode_cache.active_objects")
	m.data.SetDescription("NFS inode Cache Cache Active Objects")
	m.data.SetUnit("{count}")
	m.data.SetEmptyGauge()
}

func (m *metricSlabNfsInodeCacheActiveObjects) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricSlabNfsInodeCacheActiveObjects) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricSlabNfsInodeCacheActiveObjects) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricSlabNfsInodeCacheActiveObjects(cfg SlabNfsInodeCacheActiveObjectsMetricConfig) metricSlabNfsInodeCacheActiveObjects {
	m := metricSlabNfsInodeCacheActiveObjects{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricSlabNfsInodeCacheObjsize struct {
	data     pmetric.Metric                       // data buffer for generated metric.
	config   SlabNfsInodeCacheObjsizeMetricConfig // metric config provided by user.
	capacity int                                  // max observed number of data points added to the metric.
}

// init fills slab.nfs_inode_cache.objsize metric with initial data.
func (m *metricSlabNfsInodeCacheObjsize) init() {
	m.data.SetName("slab.nfs_inode_cache.objsize")
	m.data.SetDescription("NFS inode Cache Object Size")
	m.data.SetUnit("{size}")
	m.data.SetEmptyGauge()
}

func (m *metricSlabNfsInodeCacheObjsize) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricSlabNfsInodeCacheObjsize) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricSlabNfsInodeCacheObjsize) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricSlabNfsInodeCacheObjsize(cfg SlabNfsInodeCacheObjsizeMetricConfig) metricSlabNfsInodeCacheObjsize {
	m := metricSlabNfsInodeCacheObjsize{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                               MetricsBuilderConfig // config of the metrics builder.
	startTime                            pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                      int                  // maximum observed number of metrics per resource.
	metricsBuffer                        pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                            component.BuildInfo  // contains version information.
	metricSlabDentryCacheActiveObjects   metricSlabDentryCacheActiveObjects
	metricSlabDentryCacheObjsize         metricSlabDentryCacheObjsize
	metricSlabNfsInodeCacheActiveObjects metricSlabNfsInodeCacheActiveObjects
	metricSlabNfsInodeCacheObjsize       metricSlabNfsInodeCacheObjsize
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                               mbc,
		startTime:                            pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                        pmetric.NewMetrics(),
		buildInfo:                            settings.BuildInfo,
		metricSlabDentryCacheActiveObjects:   newMetricSlabDentryCacheActiveObjects(mbc.Metrics.SlabDentryCacheActiveObjects),
		metricSlabDentryCacheObjsize:         newMetricSlabDentryCacheObjsize(mbc.Metrics.SlabDentryCacheObjsize),
		metricSlabNfsInodeCacheActiveObjects: newMetricSlabNfsInodeCacheActiveObjects(mbc.Metrics.SlabNfsInodeCacheActiveObjects),
		metricSlabNfsInodeCacheObjsize:       newMetricSlabNfsInodeCacheObjsize(mbc.Metrics.SlabNfsInodeCacheObjsize),
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricSlabDentryCacheActiveObjects.emit(ils.Metrics())
	mb.metricSlabDentryCacheObjsize.emit(ils.Metrics())
	mb.metricSlabNfsInodeCacheActiveObjects.emit(ils.Metrics())
	mb.metricSlabNfsInodeCacheObjsize.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordSlabDentryCacheActiveObjectsDataPoint adds a data point to slab.dentry_cache.active_objects metric.
func (mb *MetricsBuilder) RecordSlabDentryCacheActiveObjectsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricSlabDentryCacheActiveObjects.recordDataPoint(mb.startTime, ts, val)
}

// RecordSlabDentryCacheObjsizeDataPoint adds a data point to slab.dentry_cache.objsize metric.
func (mb *MetricsBuilder) RecordSlabDentryCacheObjsizeDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricSlabDentryCacheObjsize.recordDataPoint(mb.startTime, ts, val)
}

// RecordSlabNfsInodeCacheActiveObjectsDataPoint adds a data point to slab.nfs_inode_cache.active_objects metric.
func (mb *MetricsBuilder) RecordSlabNfsInodeCacheActiveObjectsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricSlabNfsInodeCacheActiveObjects.recordDataPoint(mb.startTime, ts, val)
}

// RecordSlabNfsInodeCacheObjsizeDataPoint adds a data point to slab.nfs_inode_cache.objsize metric.
func (mb *MetricsBuilder) RecordSlabNfsInodeCacheObjsizeDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricSlabNfsInodeCacheObjsize.recordDataPoint(mb.startTime, ts, val)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
