// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					NfsPacketsArrived: NfsPacketsArrivedMetricConfig{
						Enabled: true,
					},
					NfsPacketsDeferred: NfsPacketsDeferredMetricConfig{
						Enabled: true,
					},
					NfsSocketsEnqueued: NfsSocketsEnqueuedMetricConfig{
						Enabled: true,
					},
					NfsThreads: NfsThreadsMetricConfig{
						Enabled: true,
					},
					NfsThreadsTimedout: NfsThreadsTimedoutMetricConfig{
						Enabled: true,
					},
					NfsThreadsWoken: NfsThreadsWokenMetricConfig{
						Enabled: true,
					},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					NfsPacketsArrived: NfsPacketsArrivedMetricConfig{
						Enabled: false,
					},
					NfsPacketsDeferred: NfsPacketsDeferredMetricConfig{
						Enabled: false,
					},
					NfsSocketsEnqueued: NfsSocketsEnqueuedMetricConfig{
						Enabled: false,
					},
					NfsThreads: NfsThreadsMetricConfig{
						Enabled: false,
					},
					NfsThreadsTimedout: NfsThreadsTimedoutMetricConfig{
						Enabled: false,
					},
					NfsThreadsWoken: NfsThreadsWokenMetricConfig{
						Enabled: false,
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(NfsPacketsArrivedMetricConfig{}, NfsPacketsDeferredMetricConfig{}, NfsSocketsEnqueuedMetricConfig{}, NfsThreadsMetricConfig{}, NfsThreadsTimedoutMetricConfig{}, NfsThreadsWokenMetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
