// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for nfsd metrics.
type MetricsConfig struct {
	NfsPacketsArrived  MetricConfig `mapstructure:"nfs.packets.arrived"`
	NfsPacketsDeferred MetricConfig `mapstructure:"nfs.packets.deferred"`
	NfsSocketsEnqueued MetricConfig `mapstructure:"nfs.sockets.enqueued"`
	NfsThreads         MetricConfig `mapstructure:"nfs.threads"`
	NfsThreadsTimedout MetricConfig `mapstructure:"nfs.threads.timedout"`
	NfsThreadsWoken    MetricConfig `mapstructure:"nfs.threads.woken"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		NfsPacketsArrived: MetricConfig{
			Enabled: true,
		},
		NfsPacketsDeferred: MetricConfig{
			Enabled: true,
		},
		NfsSocketsEnqueued: MetricConfig{
			Enabled: true,
		},
		NfsThreads: MetricConfig{
			Enabled: true,
		},
		NfsThreadsTimedout: MetricConfig{
			Enabled: true,
		},
		NfsThreadsWoken: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for nfsd metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
