// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
	"time"
)

const (
	AggregationStrategySum = "sum"
	AggregationStrategyAvg = "avg"
	AggregationStrategyMin = "min"
	AggregationStrategyMax = "max"
)

var MetricsInfo = metricsInfo{
	NfsPacketsArrived: metricInfo{
		Name: "nfs.packets.arrived",
	},
	NfsPacketsDeferred: metricInfo{
		Name: "nfs.packets.deferred",
	},
	NfsSocketsEnqueued: metricInfo{
		Name: "nfs.sockets.enqueued",
	},
	NfsThreads: metricInfo{
		Name: "nfs.threads",
	},
	NfsThreadsTimedout: metricInfo{
		Name: "nfs.threads.timedout",
	},
	NfsThreadsWoken: metricInfo{
		Name: "nfs.threads.woken",
	},
}

type metricsInfo struct {
	NfsPacketsArrived  metricInfo
	NfsPacketsDeferred metricInfo
	NfsSocketsEnqueued metricInfo
	NfsThreads         metricInfo
	NfsThreadsTimedout metricInfo
	NfsThreadsWoken    metricInfo
}

type metricInfo struct {
	Name       string
	Attributes []string
}

type metricNfsPacketsArrived struct {
	data     pmetric.Metric                // data buffer for generated metric.
	config   NfsPacketsArrivedMetricConfig // metric config provided by user.
	capacity int                           // max observed number of data points added to the metric.
}

// init fills nfs.packets.arrived metric with initial data.
func (m *metricNfsPacketsArrived) init() {
	m.data.SetName("nfs.packets.arrived")
	m.data.SetDescription("Number of NFS packets arrived")
	m.data.SetUnit("{packets}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNfsPacketsArrived) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsPacketsArrived) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsPacketsArrived) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsPacketsArrived(cfg NfsPacketsArrivedMetricConfig) metricNfsPacketsArrived {
	m := metricNfsPacketsArrived{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsPacketsDeferred struct {
	data     pmetric.Metric                 // data buffer for generated metric.
	config   NfsPacketsDeferredMetricConfig // metric config provided by user.
	capacity int                            // max observed number of data points added to the metric.
}

// init fills nfs.packets.deferred metric with initial data.
func (m *metricNfsPacketsDeferred) init() {
	m.data.SetName("nfs.packets.deferred")
	m.data.SetDescription("Number of NFS packets deferred")
	m.data.SetUnit("{packets}")
	m.data.SetEmptyGauge()
}

func (m *metricNfsPacketsDeferred) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsPacketsDeferred) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsPacketsDeferred) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsPacketsDeferred(cfg NfsPacketsDeferredMetricConfig) metricNfsPacketsDeferred {
	m := metricNfsPacketsDeferred{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsSocketsEnqueued struct {
	data     pmetric.Metric                 // data buffer for generated metric.
	config   NfsSocketsEnqueuedMetricConfig // metric config provided by user.
	capacity int                            // max observed number of data points added to the metric.
}

// init fills nfs.sockets.enqueued metric with initial data.
func (m *metricNfsSocketsEnqueued) init() {
	m.data.SetName("nfs.sockets.enqueued")
	m.data.SetDescription("Number of times an NFS transport is enqueued to wait for an NFS thread to service")
	m.data.SetUnit("{count}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNfsSocketsEnqueued) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsSocketsEnqueued) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsSocketsEnqueued) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsSocketsEnqueued(cfg NfsSocketsEnqueuedMetricConfig) metricNfsSocketsEnqueued {
	m := metricNfsSocketsEnqueued{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsThreads struct {
	data     pmetric.Metric         // data buffer for generated metric.
	config   NfsThreadsMetricConfig // metric config provided by user.
	capacity int                    // max observed number of data points added to the metric.
}

// init fills nfs.threads metric with initial data.
func (m *metricNfsThreads) init() {
	m.data.SetName("nfs.threads")
	m.data.SetDescription("Number of current KNFSD server threads")
	m.data.SetUnit("{threads}")
	m.data.SetEmptyGauge()
}

func (m *metricNfsThreads) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsThreads) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsThreads) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsThreads(cfg NfsThreadsMetricConfig) metricNfsThreads {
	m := metricNfsThreads{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsThreadsTimedout struct {
	data     pmetric.Metric                 // data buffer for generated metric.
	config   NfsThreadsTimedoutMetricConfig // metric config provided by user.
	capacity int                            // max observed number of data points added to the metric.
}

// init fills nfs.threads.timedout metric with initial data.
func (m *metricNfsThreadsTimedout) init() {
	m.data.SetName("nfs.threads.timedout")
	m.data.SetDescription("Number of times an NFS thread triggered an idle timeout")
	m.data.SetUnit("{count}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNfsThreadsTimedout) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsThreadsTimedout) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsThreadsTimedout) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsThreadsTimedout(cfg NfsThreadsTimedoutMetricConfig) metricNfsThreadsTimedout {
	m := metricNfsThreadsTimedout{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsThreadsWoken struct {
	data     pmetric.Metric              // data buffer for generated metric.
	config   NfsThreadsWokenMetricConfig // metric config provided by user.
	capacity int                         // max observed number of data points added to the metric.
}

// init fills nfs.threads.woken metric with initial data.
func (m *metricNfsThreadsWoken) init() {
	m.data.SetName("nfs.threads.woken")
	m.data.SetDescription("Number of times an idle NFS thread is woken to receive some data from an NFS transport")
	m.data.SetUnit("{count}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNfsThreadsWoken) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsThreadsWoken) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsThreadsWoken) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsThreadsWoken(cfg NfsThreadsWokenMetricConfig) metricNfsThreadsWoken {
	m := metricNfsThreadsWoken{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                   MetricsBuilderConfig // config of the metrics builder.
	startTime                pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity          int                  // maximum observed number of metrics per resource.
	metricsBuffer            pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                component.BuildInfo  // contains version information.
	metricNfsPacketsArrived  metricNfsPacketsArrived
	metricNfsPacketsDeferred metricNfsPacketsDeferred
	metricNfsSocketsEnqueued metricNfsSocketsEnqueued
	metricNfsThreads         metricNfsThreads
	metricNfsThreadsTimedout metricNfsThreadsTimedout
	metricNfsThreadsWoken    metricNfsThreadsWoken
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                   mbc,
		startTime:                pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:            pmetric.NewMetrics(),
		buildInfo:                settings.BuildInfo,
		metricNfsPacketsArrived:  newMetricNfsPacketsArrived(mbc.Metrics.NfsPacketsArrived),
		metricNfsPacketsDeferred: newMetricNfsPacketsDeferred(mbc.Metrics.NfsPacketsDeferred),
		metricNfsSocketsEnqueued: newMetricNfsSocketsEnqueued(mbc.Metrics.NfsSocketsEnqueued),
		metricNfsThreads:         newMetricNfsThreads(mbc.Metrics.NfsThreads),
		metricNfsThreadsTimedout: newMetricNfsThreadsTimedout(mbc.Metrics.NfsThreadsTimedout),
		metricNfsThreadsWoken:    newMetricNfsThreadsWoken(mbc.Metrics.NfsThreadsWoken),
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricNfsPacketsArrived.emit(ils.Metrics())
	mb.metricNfsPacketsDeferred.emit(ils.Metrics())
	mb.metricNfsSocketsEnqueued.emit(ils.Metrics())
	mb.metricNfsThreads.emit(ils.Metrics())
	mb.metricNfsThreadsTimedout.emit(ils.Metrics())
	mb.metricNfsThreadsWoken.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordNfsPacketsArrivedDataPoint adds a data point to nfs.packets.arrived metric.
func (mb *MetricsBuilder) RecordNfsPacketsArrivedDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNfsPacketsArrived.recordDataPoint(mb.startTime, ts, val)
}

// RecordNfsPacketsDeferredDataPoint adds a data point to nfs.packets.deferred metric.
func (mb *MetricsBuilder) RecordNfsPacketsDeferredDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNfsPacketsDeferred.recordDataPoint(mb.startTime, ts, val)
}

// RecordNfsSocketsEnqueuedDataPoint adds a data point to nfs.sockets.enqueued metric.
func (mb *MetricsBuilder) RecordNfsSocketsEnqueuedDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNfsSocketsEnqueued.recordDataPoint(mb.startTime, ts, val)
}

// RecordNfsThreadsDataPoint adds a data point to nfs.threads metric.
func (mb *MetricsBuilder) RecordNfsThreadsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNfsThreads.recordDataPoint(mb.startTime, ts, val)
}

// RecordNfsThreadsTimedoutDataPoint adds a data point to nfs.threads.timedout metric.
func (mb *MetricsBuilder) RecordNfsThreadsTimedoutDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNfsThreadsTimedout.recordDataPoint(mb.startTime, ts, val)
}

// RecordNfsThreadsWokenDataPoint adds a data point to nfs.threads.woken metric.
func (mb *MetricsBuilder) RecordNfsThreadsWokenDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNfsThreadsWoken.recordDataPoint(mb.startTime, ts, val)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
