// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// NfsPacketsArrivedMetricConfig provides config for the nfs.packets.arrived metric.
type NfsPacketsArrivedMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsPacketsArrivedMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// NfsPacketsDeferredMetricConfig provides config for the nfs.packets.deferred metric.
type NfsPacketsDeferredMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsPacketsDeferredMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// NfsSocketsEnqueuedMetricConfig provides config for the nfs.sockets.enqueued metric.
type NfsSocketsEnqueuedMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsSocketsEnqueuedMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// NfsThreadsMetricConfig provides config for the nfs.threads metric.
type NfsThreadsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsThreadsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// NfsThreadsTimedoutMetricConfig provides config for the nfs.threads.timedout metric.
type NfsThreadsTimedoutMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsThreadsTimedoutMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// NfsThreadsWokenMetricConfig provides config for the nfs.threads.woken metric.
type NfsThreadsWokenMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsThreadsWokenMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for nfsd metrics.
type MetricsConfig struct {
	NfsPacketsArrived  NfsPacketsArrivedMetricConfig  `mapstructure:"nfs.packets.arrived"`
	NfsPacketsDeferred NfsPacketsDeferredMetricConfig `mapstructure:"nfs.packets.deferred"`
	NfsSocketsEnqueued NfsSocketsEnqueuedMetricConfig `mapstructure:"nfs.sockets.enqueued"`
	NfsThreads         NfsThreadsMetricConfig         `mapstructure:"nfs.threads"`
	NfsThreadsTimedout NfsThreadsTimedoutMetricConfig `mapstructure:"nfs.threads.timedout"`
	NfsThreadsWoken    NfsThreadsWokenMetricConfig    `mapstructure:"nfs.threads.woken"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		NfsPacketsArrived: NfsPacketsArrivedMetricConfig{
			Enabled: true,
		},
		NfsPacketsDeferred: NfsPacketsDeferredMetricConfig{
			Enabled: true,
		},
		NfsSocketsEnqueued: NfsSocketsEnqueuedMetricConfig{
			Enabled: true,
		},
		NfsThreads: NfsThreadsMetricConfig{
			Enabled: true,
		},
		NfsThreadsTimedout: NfsThreadsTimedoutMetricConfig{
			Enabled: true,
		},
		NfsThreadsWoken: NfsThreadsWokenMetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for nfsd metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
