#!/usr/bin/env bash

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

# This script is used to generate the THIRD-PARTY-LICENSES file,
# which lists the licenses of the project's referenced dependencies.

# run this script from the .devcontainer/dev dir
cd ../..
rm -f THIRD-PARTY-LICENSES
make lic-scan > THIRD-PARTY-LICENSES

# remove first 3 lines
sed -i '1,3d' THIRD-PARTY-LICENSES

# add text
sed -i "1i See '.trivyignore.yaml' for a list of licenses ignored as acceptable in future Trivy scans." THIRD-PARTY-LICENSES
sed -i "1i This report was generated by 'https://github.com/aquasecurity/trivy' on $(date), listing the licenses of the dependencies referenced in the project.\n" THIRD-PARTY-LICENSES
