// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// NfsClientsMetricConfig provides config for the nfs.clients metric.
type NfsClientsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsClientsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// NfsConnectionsMetricConfig provides config for the nfs.connections metric.
type NfsConnectionsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsConnectionsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for connections metrics.
type MetricsConfig struct {
	NfsClients     NfsClientsMetricConfig     `mapstructure:"nfs.clients"`
	NfsConnections NfsConnectionsMetricConfig `mapstructure:"nfs.connections"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		NfsClients: NfsClientsMetricConfig{
			Enabled: true,
		},
		NfsConnections: NfsConnectionsMetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for connections metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
