# Disable mount point expiry to avoid stale file handles, especially when
# using the crossmnt option.
# https://manpages.ubuntu.com/manpages/noble/man5/nfs.conf.5.html
options nfs nfs_mountpoint_expiry_timeout=-1
options nfs callback_tcpport=20055
options lockd nlm_tcpport=20050 nlm_udpport=20050
