// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/fscache component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("fscache")
	ScopeName = "knfsd-metrics-agent/fscache"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
