// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for fscache metrics.
type MetricsConfig struct {
	FscacheAcquireOk               MetricConfig `mapstructure:"fscache.acquire.ok"`
	FscacheAcquireOom              MetricConfig `mapstructure:"fscache.acquire.oom"`
	FscacheAcquireRequests         MetricConfig `mapstructure:"fscache.acquire.requests"`
	FscacheCookiesData             MetricConfig `mapstructure:"fscache.cookies.data"`
	FscacheCookiesVolume           MetricConfig `mapstructure:"fscache.cookies.volume"`
	FscacheCookiesVolumeCollisions MetricConfig `mapstructure:"fscache.cookies.volume_collisions"`
	FscacheCookiesVolumeOom        MetricConfig `mapstructure:"fscache.cookies.volume_oom"`
	FscacheInvalidations           MetricConfig `mapstructure:"fscache.invalidations"`
	FscacheIoMisfit                MetricConfig `mapstructure:"fscache.io.misfit"`
	FscacheIoRead                  MetricConfig `mapstructure:"fscache.io.read"`
	FscacheIoWrite                 MetricConfig `mapstructure:"fscache.io.write"`
	FscacheLruCount                MetricConfig `mapstructure:"fscache.lru.count"`
	FscacheLruDropped              MetricConfig `mapstructure:"fscache.lru.dropped"`
	FscacheLruExpired              MetricConfig `mapstructure:"fscache.lru.expired"`
	FscacheLruRemoved              MetricConfig `mapstructure:"fscache.lru.removed"`
	FscacheNospaceCreate           MetricConfig `mapstructure:"fscache.nospace.create"`
	FscacheNospaceCull             MetricConfig `mapstructure:"fscache.nospace.cull"`
	FscacheNospaceWrite            MetricConfig `mapstructure:"fscache.nospace.write"`
	FscacheRelinquishDrop          MetricConfig `mapstructure:"fscache.relinquish.drop"`
	FscacheRelinquishRequests      MetricConfig `mapstructure:"fscache.relinquish.requests"`
	FscacheRelinquishRetire        MetricConfig `mapstructure:"fscache.relinquish.retire"`
	FscacheUpdatesRequests         MetricConfig `mapstructure:"fscache.updates.requests"`
	FscacheUpdatesResize           MetricConfig `mapstructure:"fscache.updates.resize"`
	FscacheUpdatesResizeSkipped    MetricConfig `mapstructure:"fscache.updates.resize_skipped"`
	NetfsCacheReadDone             MetricConfig `mapstructure:"netfs.cache_read.done"`
	NetfsCacheReadFailed           MetricConfig `mapstructure:"netfs.cache_read.failed"`
	NetfsCacheReadRequests         MetricConfig `mapstructure:"netfs.cache_read.requests"`
	NetfsCacheWriteDone            MetricConfig `mapstructure:"netfs.cache_write.done"`
	NetfsCacheWriteFailed          MetricConfig `mapstructure:"netfs.cache_write.failed"`
	NetfsCacheWriteRequests        MetricConfig `mapstructure:"netfs.cache_write.requests"`
	NetfsDownloadDone              MetricConfig `mapstructure:"netfs.download.done"`
	NetfsDownloadFailed            MetricConfig `mapstructure:"netfs.download.failed"`
	NetfsDownloadInstead           MetricConfig `mapstructure:"netfs.download.instead"`
	NetfsDownloadRequests          MetricConfig `mapstructure:"netfs.download.requests"`
	NetfsObjectsFolioQueue         MetricConfig `mapstructure:"netfs.objects.folio_queue"`
	NetfsObjectsReadReqs           MetricConfig `mapstructure:"netfs.objects.read_reqs"`
	NetfsObjectsSubreqs            MetricConfig `mapstructure:"netfs.objects.subreqs"`
	NetfsObjectsWriteConflicts     MetricConfig `mapstructure:"netfs.objects.write_conflicts"`
	NetfsReadsDirect               MetricConfig `mapstructure:"netfs.reads.direct"`
	NetfsReadsFolio                MetricConfig `mapstructure:"netfs.reads.folio"`
	NetfsReadsReadahead            MetricConfig `mapstructure:"netfs.reads.readahead"`
	NetfsReadsSingle               MetricConfig `mapstructure:"netfs.reads.single"`
	NetfsReadsWriteBegin           MetricConfig `mapstructure:"netfs.reads.write_begin"`
	NetfsReadsWriteZskip           MetricConfig `mapstructure:"netfs.reads.write_zskip"`
	NetfsRetriesReadReq            MetricConfig `mapstructure:"netfs.retries.read_req"`
	NetfsRetriesReadSubreq         MetricConfig `mapstructure:"netfs.retries.read_subreq"`
	NetfsRetriesWriteReq           MetricConfig `mapstructure:"netfs.retries.write_req"`
	NetfsRetriesWriteSubreq        MetricConfig `mapstructure:"netfs.retries.write_subreq"`
	NetfsUploadDone                MetricConfig `mapstructure:"netfs.upload.done"`
	NetfsUploadFailed              MetricConfig `mapstructure:"netfs.upload.failed"`
	NetfsUploadRequests            MetricConfig `mapstructure:"netfs.upload.requests"`
	NetfsWblockSkip                MetricConfig `mapstructure:"netfs.wblock.skip"`
	NetfsWblockWait                MetricConfig `mapstructure:"netfs.wblock.wait"`
	NetfsWritesBuffered            MetricConfig `mapstructure:"netfs.writes.buffered"`
	NetfsWritesCopyToCache         MetricConfig `mapstructure:"netfs.writes.copy_to_cache"`
	NetfsWritesDirect              MetricConfig `mapstructure:"netfs.writes.direct"`
	NetfsWritesPages               MetricConfig `mapstructure:"netfs.writes.pages"`
	NetfsWritesWritethrough        MetricConfig `mapstructure:"netfs.writes.writethrough"`
	NetfsZeroOpsShort              MetricConfig `mapstructure:"netfs.zero_ops.short"`
	NetfsZeroOpsSkip               MetricConfig `mapstructure:"netfs.zero_ops.skip"`
	NetfsZeroOpsZero               MetricConfig `mapstructure:"netfs.zero_ops.zero"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		FscacheAcquireOk: MetricConfig{
			Enabled: true,
		},
		FscacheAcquireOom: MetricConfig{
			Enabled: true,
		},
		FscacheAcquireRequests: MetricConfig{
			Enabled: true,
		},
		FscacheCookiesData: MetricConfig{
			Enabled: true,
		},
		FscacheCookiesVolume: MetricConfig{
			Enabled: true,
		},
		FscacheCookiesVolumeCollisions: MetricConfig{
			Enabled: true,
		},
		FscacheCookiesVolumeOom: MetricConfig{
			Enabled: true,
		},
		FscacheInvalidations: MetricConfig{
			Enabled: true,
		},
		FscacheIoMisfit: MetricConfig{
			Enabled: true,
		},
		FscacheIoRead: MetricConfig{
			Enabled: true,
		},
		FscacheIoWrite: MetricConfig{
			Enabled: true,
		},
		FscacheLruCount: MetricConfig{
			Enabled: true,
		},
		FscacheLruDropped: MetricConfig{
			Enabled: true,
		},
		FscacheLruExpired: MetricConfig{
			Enabled: true,
		},
		FscacheLruRemoved: MetricConfig{
			Enabled: true,
		},
		FscacheNospaceCreate: MetricConfig{
			Enabled: true,
		},
		FscacheNospaceCull: MetricConfig{
			Enabled: true,
		},
		FscacheNospaceWrite: MetricConfig{
			Enabled: true,
		},
		FscacheRelinquishDrop: MetricConfig{
			Enabled: true,
		},
		FscacheRelinquishRequests: MetricConfig{
			Enabled: true,
		},
		FscacheRelinquishRetire: MetricConfig{
			Enabled: true,
		},
		FscacheUpdatesRequests: MetricConfig{
			Enabled: true,
		},
		FscacheUpdatesResize: MetricConfig{
			Enabled: true,
		},
		FscacheUpdatesResizeSkipped: MetricConfig{
			Enabled: true,
		},
		NetfsCacheReadDone: MetricConfig{
			Enabled: true,
		},
		NetfsCacheReadFailed: MetricConfig{
			Enabled: true,
		},
		NetfsCacheReadRequests: MetricConfig{
			Enabled: true,
		},
		NetfsCacheWriteDone: MetricConfig{
			Enabled: true,
		},
		NetfsCacheWriteFailed: MetricConfig{
			Enabled: true,
		},
		NetfsCacheWriteRequests: MetricConfig{
			Enabled: true,
		},
		NetfsDownloadDone: MetricConfig{
			Enabled: true,
		},
		NetfsDownloadFailed: MetricConfig{
			Enabled: true,
		},
		NetfsDownloadInstead: MetricConfig{
			Enabled: true,
		},
		NetfsDownloadRequests: MetricConfig{
			Enabled: true,
		},
		NetfsObjectsFolioQueue: MetricConfig{
			Enabled: true,
		},
		NetfsObjectsReadReqs: MetricConfig{
			Enabled: true,
		},
		NetfsObjectsSubreqs: MetricConfig{
			Enabled: true,
		},
		NetfsObjectsWriteConflicts: MetricConfig{
			Enabled: true,
		},
		NetfsReadsDirect: MetricConfig{
			Enabled: true,
		},
		NetfsReadsFolio: MetricConfig{
			Enabled: true,
		},
		NetfsReadsReadahead: MetricConfig{
			Enabled: true,
		},
		NetfsReadsSingle: MetricConfig{
			Enabled: true,
		},
		NetfsReadsWriteBegin: MetricConfig{
			Enabled: true,
		},
		NetfsReadsWriteZskip: MetricConfig{
			Enabled: true,
		},
		NetfsRetriesReadReq: MetricConfig{
			Enabled: true,
		},
		NetfsRetriesReadSubreq: MetricConfig{
			Enabled: true,
		},
		NetfsRetriesWriteReq: MetricConfig{
			Enabled: true,
		},
		NetfsRetriesWriteSubreq: MetricConfig{
			Enabled: true,
		},
		NetfsUploadDone: MetricConfig{
			Enabled: true,
		},
		NetfsUploadFailed: MetricConfig{
			Enabled: true,
		},
		NetfsUploadRequests: MetricConfig{
			Enabled: true,
		},
		NetfsWblockSkip: MetricConfig{
			Enabled: true,
		},
		NetfsWblockWait: MetricConfig{
			Enabled: true,
		},
		NetfsWritesBuffered: MetricConfig{
			Enabled: true,
		},
		NetfsWritesCopyToCache: MetricConfig{
			Enabled: true,
		},
		NetfsWritesDirect: MetricConfig{
			Enabled: true,
		},
		NetfsWritesPages: MetricConfig{
			Enabled: true,
		},
		NetfsWritesWritethrough: MetricConfig{
			Enabled: true,
		},
		NetfsZeroOpsShort: MetricConfig{
			Enabled: true,
		},
		NetfsZeroOpsSkip: MetricConfig{
			Enabled: true,
		},
		NetfsZeroOpsZero: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for fscache metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
