// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0
			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheAcquireOkDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheAcquireOomDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheAcquireRequestsDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheCookiesDataDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheCookiesVolumeDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheCookiesVolumeCollisionsDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheCookiesVolumeOomDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheInvalidationsDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheIoMisfitDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheIoReadDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheIoWriteDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheLruCountDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheLruDroppedDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheLruExpiredDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheLruRemovedDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheNospaceCreateDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheNospaceCullDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheNospaceWriteDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheRelinquishDropDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheRelinquishRequestsDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheRelinquishRetireDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheUpdatesRequestsDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheUpdatesResizeDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFscacheUpdatesResizeSkippedDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsCacheReadDoneDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsCacheReadFailedDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsCacheReadRequestsDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsCacheWriteDoneDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsCacheWriteFailedDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsCacheWriteRequestsDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsDownloadDoneDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsDownloadFailedDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsDownloadInsteadDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsDownloadRequestsDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsObjectsFolioQueueDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsObjectsReadReqsDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsObjectsSubreqsDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsObjectsWriteConflictsDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsReadsDirectDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsReadsFolioDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsReadsReadaheadDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsReadsSingleDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsReadsWriteBeginDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsReadsWriteZskipDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsRetriesReadReqDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsRetriesReadSubreqDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsRetriesWriteReqDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsRetriesWriteSubreqDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsUploadDoneDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsUploadFailedDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsUploadRequestsDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsWblockSkipDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsWblockWaitDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsWritesBufferedDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsWritesCopyToCacheDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsWritesDirectDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsWritesPagesDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsWritesWritethroughDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsZeroOpsShortDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsZeroOpsSkipDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetfsZeroOpsZeroDataPoint(ts, 1)

			res := pcommon.NewResource()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "fscache.acquire.ok":
					assert.False(t, validatedMetrics["fscache.acquire.ok"], "Found a duplicate in the metrics slice: fscache.acquire.ok")
					validatedMetrics["fscache.acquire.ok"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of acquire requests that succeeded", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.acquire.oom":
					assert.False(t, validatedMetrics["fscache.acquire.oom"], "Found a duplicate in the metrics slice: fscache.acquire.oom")
					validatedMetrics["fscache.acquire.oom"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of acquire requests that failed due to ENOMEM", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.acquire.requests":
					assert.False(t, validatedMetrics["fscache.acquire.requests"], "Found a duplicate in the metrics slice: fscache.acquire.requests")
					validatedMetrics["fscache.acquire.requests"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of acquire cookie requests", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.cookies.data":
					assert.False(t, validatedMetrics["fscache.cookies.data"], "Found a duplicate in the metrics slice: fscache.cookies.data")
					validatedMetrics["fscache.cookies.data"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of data storage cookies allocated", mi.Description())
					assert.Equal(t, "{cookies}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.cookies.volume":
					assert.False(t, validatedMetrics["fscache.cookies.volume"], "Found a duplicate in the metrics slice: fscache.cookies.volume")
					validatedMetrics["fscache.cookies.volume"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of volume index cookies allocated", mi.Description())
					assert.Equal(t, "{cookies}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.cookies.volume_collisions":
					assert.False(t, validatedMetrics["fscache.cookies.volume_collisions"], "Found a duplicate in the metrics slice: fscache.cookies.volume_collisions")
					validatedMetrics["fscache.cookies.volume_collisions"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of volume index key collisions", mi.Description())
					assert.Equal(t, "{collisions}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.cookies.volume_oom":
					assert.False(t, validatedMetrics["fscache.cookies.volume_oom"], "Found a duplicate in the metrics slice: fscache.cookies.volume_oom")
					validatedMetrics["fscache.cookies.volume_oom"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of OOM events when allocating volume cookies", mi.Description())
					assert.Equal(t, "{events}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.invalidations":
					assert.False(t, validatedMetrics["fscache.invalidations"], "Found a duplicate in the metrics slice: fscache.invalidations")
					validatedMetrics["fscache.invalidations"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of invalidations", mi.Description())
					assert.Equal(t, "{invalidations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.io.misfit":
					assert.False(t, validatedMetrics["fscache.io.misfit"], "Found a duplicate in the metrics slice: fscache.io.misfit")
					validatedMetrics["fscache.io.misfit"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of DIO misfit operations", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.io.read":
					assert.False(t, validatedMetrics["fscache.io.read"], "Found a duplicate in the metrics slice: fscache.io.read")
					validatedMetrics["fscache.io.read"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of read operations in the cache", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.io.write":
					assert.False(t, validatedMetrics["fscache.io.write"], "Found a duplicate in the metrics slice: fscache.io.write")
					validatedMetrics["fscache.io.write"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of write operations in the cache", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.lru.count":
					assert.False(t, validatedMetrics["fscache.lru.count"], "Found a duplicate in the metrics slice: fscache.lru.count")
					validatedMetrics["fscache.lru.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of cookies currently on the LRU", mi.Description())
					assert.Equal(t, "{cookies}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.lru.dropped":
					assert.False(t, validatedMetrics["fscache.lru.dropped"], "Found a duplicate in the metrics slice: fscache.lru.dropped")
					validatedMetrics["fscache.lru.dropped"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of LRU'd cookies relinquished or withdrawn", mi.Description())
					assert.Equal(t, "{cookies}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.lru.expired":
					assert.False(t, validatedMetrics["fscache.lru.expired"], "Found a duplicate in the metrics slice: fscache.lru.expired")
					validatedMetrics["fscache.lru.expired"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of cookies expired off of the LRU", mi.Description())
					assert.Equal(t, "{cookies}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.lru.removed":
					assert.False(t, validatedMetrics["fscache.lru.removed"], "Found a duplicate in the metrics slice: fscache.lru.removed")
					validatedMetrics["fscache.lru.removed"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of cookies removed from the LRU", mi.Description())
					assert.Equal(t, "{cookies}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.nospace.create":
					assert.False(t, validatedMetrics["fscache.nospace.create"], "Found a duplicate in the metrics slice: fscache.nospace.create")
					validatedMetrics["fscache.nospace.create"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of create requests refused due to lack of space", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.nospace.cull":
					assert.False(t, validatedMetrics["fscache.nospace.cull"], "Found a duplicate in the metrics slice: fscache.nospace.cull")
					validatedMetrics["fscache.nospace.cull"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of objects culled to make space", mi.Description())
					assert.Equal(t, "{objects}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.nospace.write":
					assert.False(t, validatedMetrics["fscache.nospace.write"], "Found a duplicate in the metrics slice: fscache.nospace.write")
					validatedMetrics["fscache.nospace.write"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of write requests refused due to lack of space", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.relinquish.drop":
					assert.False(t, validatedMetrics["fscache.relinquish.drop"], "Found a duplicate in the metrics slice: fscache.relinquish.drop")
					validatedMetrics["fscache.relinquish.drop"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of cookies no longer blocking re-acquisition", mi.Description())
					assert.Equal(t, "{cookies}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.relinquish.requests":
					assert.False(t, validatedMetrics["fscache.relinquish.requests"], "Found a duplicate in the metrics slice: fscache.relinquish.requests")
					validatedMetrics["fscache.relinquish.requests"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of relinquish cookie requests", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.relinquish.retire":
					assert.False(t, validatedMetrics["fscache.relinquish.retire"], "Found a duplicate in the metrics slice: fscache.relinquish.retire")
					validatedMetrics["fscache.relinquish.retire"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of relinquish requests with retire=true", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.updates.requests":
					assert.False(t, validatedMetrics["fscache.updates.requests"], "Found a duplicate in the metrics slice: fscache.updates.requests")
					validatedMetrics["fscache.updates.requests"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of update cookie requests", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.updates.resize":
					assert.False(t, validatedMetrics["fscache.updates.resize"], "Found a duplicate in the metrics slice: fscache.updates.resize")
					validatedMetrics["fscache.updates.resize"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of resize requests", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fscache.updates.resize_skipped":
					assert.False(t, validatedMetrics["fscache.updates.resize_skipped"], "Found a duplicate in the metrics slice: fscache.updates.resize_skipped")
					validatedMetrics["fscache.updates.resize_skipped"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of skipped resize requests", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.cache_read.done":
					assert.False(t, validatedMetrics["netfs.cache_read.done"], "Found a duplicate in the metrics slice: netfs.cache_read.done")
					validatedMetrics["netfs.cache_read.done"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of cache read operations completed (netfs_n_rh_read_done)", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.cache_read.failed":
					assert.False(t, validatedMetrics["netfs.cache_read.failed"], "Found a duplicate in the metrics slice: netfs.cache_read.failed")
					validatedMetrics["netfs.cache_read.failed"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of cache read operations failed (netfs_n_rh_read_failed)", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.cache_read.requests":
					assert.False(t, validatedMetrics["netfs.cache_read.requests"], "Found a duplicate in the metrics slice: netfs.cache_read.requests")
					validatedMetrics["netfs.cache_read.requests"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of cache read requests (netfs_n_rh_read)", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.cache_write.done":
					assert.False(t, validatedMetrics["netfs.cache_write.done"], "Found a duplicate in the metrics slice: netfs.cache_write.done")
					validatedMetrics["netfs.cache_write.done"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of cache write operations completed (netfs_n_wh_write_done)", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.cache_write.failed":
					assert.False(t, validatedMetrics["netfs.cache_write.failed"], "Found a duplicate in the metrics slice: netfs.cache_write.failed")
					validatedMetrics["netfs.cache_write.failed"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of cache write operations failed (netfs_n_wh_write_failed)", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.cache_write.requests":
					assert.False(t, validatedMetrics["netfs.cache_write.requests"], "Found a duplicate in the metrics slice: netfs.cache_write.requests")
					validatedMetrics["netfs.cache_write.requests"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of cache write requests (netfs_n_wh_write)", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.download.done":
					assert.False(t, validatedMetrics["netfs.download.done"], "Found a duplicate in the metrics slice: netfs.download.done")
					validatedMetrics["netfs.download.done"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of download operations completed (netfs_n_rh_download_done)", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.download.failed":
					assert.False(t, validatedMetrics["netfs.download.failed"], "Found a duplicate in the metrics slice: netfs.download.failed")
					validatedMetrics["netfs.download.failed"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of download operations failed (netfs_n_rh_download_failed)", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.download.instead":
					assert.False(t, validatedMetrics["netfs.download.instead"], "Found a duplicate in the metrics slice: netfs.download.instead")
					validatedMetrics["netfs.download.instead"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of download instead of cache operations (netfs_n_rh_download_instead)", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.download.requests":
					assert.False(t, validatedMetrics["netfs.download.requests"], "Found a duplicate in the metrics slice: netfs.download.requests")
					validatedMetrics["netfs.download.requests"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of download requests (netfs_n_rh_download)", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.objects.folio_queue":
					assert.False(t, validatedMetrics["netfs.objects.folio_queue"], "Found a duplicate in the metrics slice: netfs.objects.folio_queue")
					validatedMetrics["netfs.objects.folio_queue"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of folio queue objects (netfs_n_folioq)", mi.Description())
					assert.Equal(t, "{objects}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.objects.read_reqs":
					assert.False(t, validatedMetrics["netfs.objects.read_reqs"], "Found a duplicate in the metrics slice: netfs.objects.read_reqs")
					validatedMetrics["netfs.objects.read_reqs"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of read request objects (netfs_n_rh_rreq)", mi.Description())
					assert.Equal(t, "{objects}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.objects.subreqs":
					assert.False(t, validatedMetrics["netfs.objects.subreqs"], "Found a duplicate in the metrics slice: netfs.objects.subreqs")
					validatedMetrics["netfs.objects.subreqs"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of subrequest objects (netfs_n_rh_sreq)", mi.Description())
					assert.Equal(t, "{objects}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.objects.write_conflicts":
					assert.False(t, validatedMetrics["netfs.objects.write_conflicts"], "Found a duplicate in the metrics slice: netfs.objects.write_conflicts")
					validatedMetrics["netfs.objects.write_conflicts"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of write stream conflicts (netfs_n_wh_wstream_conflict)", mi.Description())
					assert.Equal(t, "{conflicts}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.reads.direct":
					assert.False(t, validatedMetrics["netfs.reads.direct"], "Found a duplicate in the metrics slice: netfs.reads.direct")
					validatedMetrics["netfs.reads.direct"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of direct I/O read requests (netfs_n_rh_dio_read)", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.reads.folio":
					assert.False(t, validatedMetrics["netfs.reads.folio"], "Found a duplicate in the metrics slice: netfs.reads.folio")
					validatedMetrics["netfs.reads.folio"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of read folio requests (netfs_n_rh_read_folio)", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.reads.readahead":
					assert.False(t, validatedMetrics["netfs.reads.readahead"], "Found a duplicate in the metrics slice: netfs.reads.readahead")
					validatedMetrics["netfs.reads.readahead"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of readahead requests (netfs_n_rh_readahead)", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.reads.single":
					assert.False(t, validatedMetrics["netfs.reads.single"], "Found a duplicate in the metrics slice: netfs.reads.single")
					validatedMetrics["netfs.reads.single"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of read single requests (netfs_n_rh_read_single)", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.reads.write_begin":
					assert.False(t, validatedMetrics["netfs.reads.write_begin"], "Found a duplicate in the metrics slice: netfs.reads.write_begin")
					validatedMetrics["netfs.reads.write_begin"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of write begin requests (netfs_n_rh_write_begin)", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.reads.write_zskip":
					assert.False(t, validatedMetrics["netfs.reads.write_zskip"], "Found a duplicate in the metrics slice: netfs.reads.write_zskip")
					validatedMetrics["netfs.reads.write_zskip"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of write zero skip operations (netfs_n_rh_write_zskip)", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.retries.read_req":
					assert.False(t, validatedMetrics["netfs.retries.read_req"], "Found a duplicate in the metrics slice: netfs.retries.read_req")
					validatedMetrics["netfs.retries.read_req"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of read request retries (netfs_n_rh_retry_read_req)", mi.Description())
					assert.Equal(t, "{retries}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.retries.read_subreq":
					assert.False(t, validatedMetrics["netfs.retries.read_subreq"], "Found a duplicate in the metrics slice: netfs.retries.read_subreq")
					validatedMetrics["netfs.retries.read_subreq"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of read subrequest retries (netfs_n_rh_retry_read_subreq)", mi.Description())
					assert.Equal(t, "{retries}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.retries.write_req":
					assert.False(t, validatedMetrics["netfs.retries.write_req"], "Found a duplicate in the metrics slice: netfs.retries.write_req")
					validatedMetrics["netfs.retries.write_req"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of write request retries (netfs_n_wh_retry_write_req)", mi.Description())
					assert.Equal(t, "{retries}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.retries.write_subreq":
					assert.False(t, validatedMetrics["netfs.retries.write_subreq"], "Found a duplicate in the metrics slice: netfs.retries.write_subreq")
					validatedMetrics["netfs.retries.write_subreq"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of write subrequest retries (netfs_n_wh_retry_write_subreq)", mi.Description())
					assert.Equal(t, "{retries}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.upload.done":
					assert.False(t, validatedMetrics["netfs.upload.done"], "Found a duplicate in the metrics slice: netfs.upload.done")
					validatedMetrics["netfs.upload.done"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of upload operations completed (netfs_n_wh_upload_done)", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.upload.failed":
					assert.False(t, validatedMetrics["netfs.upload.failed"], "Found a duplicate in the metrics slice: netfs.upload.failed")
					validatedMetrics["netfs.upload.failed"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of upload operations failed (netfs_n_wh_upload_failed)", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.upload.requests":
					assert.False(t, validatedMetrics["netfs.upload.requests"], "Found a duplicate in the metrics slice: netfs.upload.requests")
					validatedMetrics["netfs.upload.requests"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of upload requests (netfs_n_wh_upload)", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.wblock.skip":
					assert.False(t, validatedMetrics["netfs.wblock.skip"], "Found a duplicate in the metrics slice: netfs.wblock.skip")
					validatedMetrics["netfs.wblock.skip"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of writeback lock skips (netfs_n_wb_lock_skip)", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.wblock.wait":
					assert.False(t, validatedMetrics["netfs.wblock.wait"], "Found a duplicate in the metrics slice: netfs.wblock.wait")
					validatedMetrics["netfs.wblock.wait"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of writeback lock waits (netfs_n_wb_lock_wait)", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.writes.buffered":
					assert.False(t, validatedMetrics["netfs.writes.buffered"], "Found a duplicate in the metrics slice: netfs.writes.buffered")
					validatedMetrics["netfs.writes.buffered"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of buffered write requests (netfs_n_wh_buffered_write)", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.writes.copy_to_cache":
					assert.False(t, validatedMetrics["netfs.writes.copy_to_cache"], "Found a duplicate in the metrics slice: netfs.writes.copy_to_cache")
					validatedMetrics["netfs.writes.copy_to_cache"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of copy to cache requests (netfs_n_wh_copy_to_cache)", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.writes.direct":
					assert.False(t, validatedMetrics["netfs.writes.direct"], "Found a duplicate in the metrics slice: netfs.writes.direct")
					validatedMetrics["netfs.writes.direct"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of direct I/O write requests (netfs_n_wh_dio_write)", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.writes.pages":
					assert.False(t, validatedMetrics["netfs.writes.pages"], "Found a duplicate in the metrics slice: netfs.writes.pages")
					validatedMetrics["netfs.writes.pages"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of write pages requests (netfs_n_wh_writepages)", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.writes.writethrough":
					assert.False(t, validatedMetrics["netfs.writes.writethrough"], "Found a duplicate in the metrics slice: netfs.writes.writethrough")
					validatedMetrics["netfs.writes.writethrough"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of writethrough requests (netfs_n_wh_writethrough)", mi.Description())
					assert.Equal(t, "{requests}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.zero_ops.short":
					assert.False(t, validatedMetrics["netfs.zero_ops.short"], "Found a duplicate in the metrics slice: netfs.zero_ops.short")
					validatedMetrics["netfs.zero_ops.short"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of short read operations (netfs_n_rh_short_read)", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.zero_ops.skip":
					assert.False(t, validatedMetrics["netfs.zero_ops.skip"], "Found a duplicate in the metrics slice: netfs.zero_ops.skip")
					validatedMetrics["netfs.zero_ops.skip"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of skip operations (netfs_n_rh_write_zskip)", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "netfs.zero_ops.zero":
					assert.False(t, validatedMetrics["netfs.zero_ops.zero"], "Found a duplicate in the metrics slice: netfs.zero_ops.zero")
					validatedMetrics["netfs.zero_ops.zero"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of zero read operations (netfs_n_rh_zero)", mi.Description())
					assert.Equal(t, "{operations}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				}
			}
		})
	}
}
