// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
	"time"
)

const (
	AggregationStrategySum = "sum"
	AggregationStrategyAvg = "avg"
	AggregationStrategyMin = "min"
	AggregationStrategyMax = "max"
)

var MetricsInfo = metricsInfo{
	NfsExportsTotalOperations: metricInfo{
		Name: "nfs.exports.total_operations",
	},
	NfsExportsTotalReadBytes: metricInfo{
		Name: "nfs.exports.total_read_bytes",
	},
	NfsExportsTotalWriteBytes: metricInfo{
		Name: "nfs.exports.total_write_bytes",
	},
}

type metricsInfo struct {
	NfsExportsTotalOperations metricInfo
	NfsExportsTotalReadBytes  metricInfo
	NfsExportsTotalWriteBytes metricInfo
}

type metricInfo struct {
	Name       string
	Attributes []string
}

type metricNfsExportsTotalOperations struct {
	data     pmetric.Metric                        // data buffer for generated metric.
	config   NfsExportsTotalOperationsMetricConfig // metric config provided by user.
	capacity int                                   // max observed number of data points added to the metric.
}

// init fills nfs.exports.total_operations metric with initial data.
func (m *metricNfsExportsTotalOperations) init() {
	m.data.SetName("nfs.exports.total_operations")
	m.data.SetDescription("Total number of NFS operations received from clients")
	m.data.SetUnit("{operations}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNfsExportsTotalOperations) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsExportsTotalOperations) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsExportsTotalOperations) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsExportsTotalOperations(cfg NfsExportsTotalOperationsMetricConfig) metricNfsExportsTotalOperations {
	m := metricNfsExportsTotalOperations{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsExportsTotalReadBytes struct {
	data     pmetric.Metric                       // data buffer for generated metric.
	config   NfsExportsTotalReadBytesMetricConfig // metric config provided by user.
	capacity int                                  // max observed number of data points added to the metric.
}

// init fills nfs.exports.total_read_bytes metric with initial data.
func (m *metricNfsExportsTotalReadBytes) init() {
	m.data.SetName("nfs.exports.total_read_bytes")
	m.data.SetDescription("Total bytes read by the NFS clients")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNfsExportsTotalReadBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsExportsTotalReadBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsExportsTotalReadBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsExportsTotalReadBytes(cfg NfsExportsTotalReadBytesMetricConfig) metricNfsExportsTotalReadBytes {
	m := metricNfsExportsTotalReadBytes{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNfsExportsTotalWriteBytes struct {
	data     pmetric.Metric                        // data buffer for generated metric.
	config   NfsExportsTotalWriteBytesMetricConfig // metric config provided by user.
	capacity int                                   // max observed number of data points added to the metric.
}

// init fills nfs.exports.total_write_bytes metric with initial data.
func (m *metricNfsExportsTotalWriteBytes) init() {
	m.data.SetName("nfs.exports.total_write_bytes")
	m.data.SetDescription("Total bytes wrote by the NFS clients")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNfsExportsTotalWriteBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsExportsTotalWriteBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsExportsTotalWriteBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNfsExportsTotalWriteBytes(cfg NfsExportsTotalWriteBytesMetricConfig) metricNfsExportsTotalWriteBytes {
	m := metricNfsExportsTotalWriteBytes{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                          MetricsBuilderConfig // config of the metrics builder.
	startTime                       pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                 int                  // maximum observed number of metrics per resource.
	metricsBuffer                   pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                       component.BuildInfo  // contains version information.
	metricNfsExportsTotalOperations metricNfsExportsTotalOperations
	metricNfsExportsTotalReadBytes  metricNfsExportsTotalReadBytes
	metricNfsExportsTotalWriteBytes metricNfsExportsTotalWriteBytes
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                          mbc,
		startTime:                       pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                   pmetric.NewMetrics(),
		buildInfo:                       settings.BuildInfo,
		metricNfsExportsTotalOperations: newMetricNfsExportsTotalOperations(mbc.Metrics.NfsExportsTotalOperations),
		metricNfsExportsTotalReadBytes:  newMetricNfsExportsTotalReadBytes(mbc.Metrics.NfsExportsTotalReadBytes),
		metricNfsExportsTotalWriteBytes: newMetricNfsExportsTotalWriteBytes(mbc.Metrics.NfsExportsTotalWriteBytes),
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricNfsExportsTotalOperations.emit(ils.Metrics())
	mb.metricNfsExportsTotalReadBytes.emit(ils.Metrics())
	mb.metricNfsExportsTotalWriteBytes.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordNfsExportsTotalOperationsDataPoint adds a data point to nfs.exports.total_operations metric.
func (mb *MetricsBuilder) RecordNfsExportsTotalOperationsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNfsExportsTotalOperations.recordDataPoint(mb.startTime, ts, val)
}

// RecordNfsExportsTotalReadBytesDataPoint adds a data point to nfs.exports.total_read_bytes metric.
func (mb *MetricsBuilder) RecordNfsExportsTotalReadBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNfsExportsTotalReadBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordNfsExportsTotalWriteBytesDataPoint adds a data point to nfs.exports.total_write_bytes metric.
func (mb *MetricsBuilder) RecordNfsExportsTotalWriteBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNfsExportsTotalWriteBytes.recordDataPoint(mb.startTime, ts, val)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
