// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for exports metrics.
type MetricsConfig struct {
	NfsExportsTotalOperations MetricConfig `mapstructure:"nfs.exports.total_operations"`
	NfsExportsTotalReadBytes  MetricConfig `mapstructure:"nfs.exports.total_read_bytes"`
	NfsExportsTotalWriteBytes MetricConfig `mapstructure:"nfs.exports.total_write_bytes"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		NfsExportsTotalOperations: MetricConfig{
			Enabled: true,
		},
		NfsExportsTotalReadBytes: MetricConfig{
			Enabled: true,
		},
		NfsExportsTotalWriteBytes: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for exports metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
