// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// NfsExportsTotalOperationsMetricConfig provides config for the nfs.exports.total_operations metric.
type NfsExportsTotalOperationsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsExportsTotalOperationsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// NfsExportsTotalReadBytesMetricConfig provides config for the nfs.exports.total_read_bytes metric.
type NfsExportsTotalReadBytesMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsExportsTotalReadBytesMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// NfsExportsTotalWriteBytesMetricConfig provides config for the nfs.exports.total_write_bytes metric.
type NfsExportsTotalWriteBytesMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsExportsTotalWriteBytesMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for exports metrics.
type MetricsConfig struct {
	NfsExportsTotalOperations NfsExportsTotalOperationsMetricConfig `mapstructure:"nfs.exports.total_operations"`
	NfsExportsTotalReadBytes  NfsExportsTotalReadBytesMetricConfig  `mapstructure:"nfs.exports.total_read_bytes"`
	NfsExportsTotalWriteBytes NfsExportsTotalWriteBytesMetricConfig `mapstructure:"nfs.exports.total_write_bytes"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		NfsExportsTotalOperations: NfsExportsTotalOperationsMetricConfig{
			Enabled: true,
		},
		NfsExportsTotalReadBytes: NfsExportsTotalReadBytesMetricConfig{
			Enabled: true,
		},
		NfsExportsTotalWriteBytes: NfsExportsTotalWriteBytesMetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for exports metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
